- Dockerfile
In Docker:
Without libmariadb-devel, the ruby gem mysql2 could not be installed.
> Added libmariadb-devel to Dockerfile Dependencies - Card 4476

- Jenkinsfile
**Notes:**
* The docker container communicates with mysql over a docker-volume-mounted-socket to act as `localhost`.
* `POSTGRES_HOST` is not needed (also the variable was never used in `config/database.yml`)
> Fixed deploy of RMT with MySQL - Card 4476

- db/migrate/20170919123818_change_product_description_to_text.rb
- db/schema.rb
Rails sets the string column type (varchar(255)) to have a limit of 255 characters in MySQL, which is not enough to fit product descriptions. The text column type should give us enough room.
> Change product description from string to text - Card 4476

- lib/rmt/downloader.rb
A return would kill the thread, so after 4 deduplicated items, the downloading would end.
> Fix Deduplication

- app/models/service.rb
- spec/models/service_spec.rb
In glue, the api appends release_stage (Alpha/Beta/...) to the product's friendly_name in the serializer. The service serializer expects the product's friendly name without the release_stage, but as the appended version is saved in the db and used, we need to make a clean version of friendly_name.
> API Fix: service name

- package/rmt-server.spec
SR for factory was declined because the if statement here could be simpler.
https://en.opensuse.org/openSUSE:Build_Service_cross_distribution_howto#Detect_a_distribution_flavor_for_special_code
> Cleaned up if statement for is_sle_12_family

- package/rmt-server.changes
changelog check on obs failed because there was no reference to removed patches
> Added removal of patches to changelog

- package/rmt-server.spec
- package/rmt.service
Puma specifies a recommended way of starting it with systemd at:
https://github.com/puma/puma/blob/5fb2df9144803f0f80ec1d9fb19d20d433706fef/docs/systemd.md#service-configuration
Type=simple can be used, and then there's not need to --daemon the Rails
server.
Additionally, we set the RAILS_LOG_TO_STDOUT variable, so that Rails
outputs its log to stdout. This allows for the logs to be saved and
visible in journalctl.
The PrivateTmp option "sets up a new file system namespace for the
executed processes and mounts private /tmp and /var/tmp directories
inside it that is not shared by processes outside of the namespace.
(...) all temporary files created by a service in these directories will
be removed after the service is stopped."
Since RMT creates some temporary directories while mirroring, …
> Use the recommended systemd config

- app/models/hw_info.rb
- db/migrate/20180420145408_remove_hw_info_uuid_index.rb
- db/schema.rb
- spec/models/hw_info_spec.rb
The unique index on 'HwInfo#uuid' breaks the behaviour in case of cleanup and attempt to register again. There should be no unique index
The solution is to update the migration and fix it on ref host manually
> Remove uniqueness for HwInfo#uuid

- app/models/product.rb
- lib/rmt/cli/products.rb
- spec/factories/products.rb
- spec/lib/rmt/cli/products_spec.rb
**Who:** RMT users
**What:** need to have mirroring enabled for recommended modules when enabling mirroring for the base product
**Why**: currently if you could do the following:
* enable `sles/15/x86_64` 
* do not enable `basesystem` or any other module
* register your client machine
* have only 3 RPM packages base product repos
* have no extensions will be listed in the output of `SUSEConnect --list-extensions`
> Enable Recommended Products - Card 170

- bin/rmt-cli
Change group and then user, otherwise, the user does not have permission
to change groups.
> Fix cli permissions

- app/models/product_predecessor_association.rb
They are provided automatically by `enum` so there's no need to
explicitly define them.
> Remove :online and :offline scopes

- .rubocop.yml
- app/controllers/api/connect/v3/systems/products_controller.rb
- app/models/repository.rb
- package/rmt-server.changes
- spec/models/repository_spec.rb
- spec/requests/api/connect/v3/systems/products_controller_spec.rb
- spec/requests/api/connect/v4/systems/products_controller_spec.rb
- spec/support/shared_examples/product_checks.rb
Needed for the use case described here https://github.com/SUSE/connect/pull/365#issuecomment-387789520
> 1. Register base product, basesystem module and server applications module on the client;
> 1. Disable server applications on RMT;
> 1. Try to de-register server applications -- I think it would also break.
> - @ikapelyukhin
Spoiler alert: It does break:
```
Error: Registration server returned 'Not all mandatory repositories are mirrored for product Server Applications Module 15 x86_64 (BETA)' (422)
```
> Skip repos check when deactivating a module/extension

- app/models/subscription.rb
Fixes https://github.com/SUSE/rmt/issues/165
The scope seems not to be used anywhere in the code
> Fix scope overriding private AR method warning

- lib/rmt/mirror.rb
- package/rmt-server.changes
- spec/lib/rmt/mirror_spec.rb
From `Dir.mktmpdir` docu:
```
The directory is created with 0700 permission. Application should not change the permission to make the temporary directory accesible from other users.
```
> Set the correct permissions for product.license directory

- app/models/product.rb
- spec/models/product_spec.rb
The previous way worked well for versions like (12, 12.1, ...), but not like (1.0, 2.0, ...). This should fix that.
> Search original and chomped version

- Dangerfile
- Makefile
Reduces number of places where the version has to be specified by one.
> Use RMT::VERSION in Makefile

- MANUAL.md
- MIGRATE.md
- README.md
- lib/rmt.rb
- lib/rmt/cli/base.rb
- lib/rmt/config.rb
- lib/suse/connect/api.rb
- package/nginx-https.conf
- package/rmt-server.changes
- package/rmt-server.spec
- spec/lib/rmt/cli/main_spec.rb
Change configuration, ssl and uuid path to make sure rmt also works on a read-only installation
https://github.com/SUSE/yast2-rmt/pull/26
Path changes:
`/usr/share/rmt/ssl` -> `/etc/rmt/ssl`
`/usr/share/rmt/config/system_uuid` -> `/var/lib/rmt/system_uuid`
`/etc/rmt.conf` -> `/etc/rmt/rmt.conf`
> Fix directory usage

- README.md
We should still document the config better, but this fixes the broken reference.
> Fix link to configuration section

- lib/rmt/fiber_request.rb
- package/rmt-server.changes
If the HTTP client fails to connect or there's an SSL issue, `on_headers` callback isn't invoked, but `on_complete` is called instead -- which never fires the error handling on the response.
This should fix the flow of things and produce meaningful error messages, e.g.:
```
WARN -- : Error while mirroring metadata: repodata/repomd.xml - return code couldnt_connect
WARN -- : Error while mirroring metadata: repodata/repomd.xml - return code ssl_cacert
```
> Emulate on_headers callback when the request failed

- package/rmt-server.spec
The builds flickered on certain older dists, because the bash-completion
directories were not yet owned by any package. Now, if they weren't
owned before, the are owned by the rmt-server package.
See similiar approach here: [IBS](https://build.suse.de/package/view_file/SUSE:SLE-15:GA/btrfsprogs/btrfsprogs.spec?expand=1)
> Fix rmt-server.spec to own bash-completion directories

- lib/rmt/mirror.rb
- package/rmt-server.changes
- spec/lib/rmt/mirror_spec.rb
Knowing whether the repository has a license file is not really
important to customers.
On the other hand, we received emails from multiple people who thought
that the message was an error (it's not).
> Remove the "No product license found" log message

- lib/rmt/cli/products.rb
- lib/rmt/cli/repos.rb
- lib/rmt/cli/repos_custom.rb
- package/rmt-server.changes
`rmt-cli p e` => `rmt-cli products enable` works
`rmt-cli p l` => `rmt-cli products list` does not
This is because thor doesn't handle the symbol well for the shortcuts.
> Fix Alias Short Commands

- lib/rmt/scc.rb
- package/rmt-server.changes
- spec/lib/rmt/scc_spec.rb
Some of the products do not have base one (for example SUMA). However, it should be possible to mirror some of them.
Right now products like that are filtered out by RMT during `sync` (SMT does not).
I suggest that we remove the check which syncs products only when they are base products so that it would be possible to mirror them.
> Sync products without base product

- app/models/migration_engine.rb
- package/rmt-server.changes
- spec/models/migration_engine_spec.rb
Sample `curl` request for verifying
```
curl -u '<SYSTEM_LOGIN>:<SYSTEM_PASSWORD>' -H "Content-type: application/json" -d '{ "installed_products": [ { "identifier": "SLES", "version": "15", "arch": "x86_64" } ], "target_base_product": { "identifier": "SLES", "version": "15.1", "arch": "x86_64" }}' -X POST http://rmt.or.scc.host:4224/connect/systems/products/offline_migrations | jq '.[] | map(.friendly_name)'
```
> Include online migration paths into offline migration

- app/models/product.rb
- package/rmt-server.changes
- spec/factories/products.rb
- spec/factories/services.rb
- spec/models/product_spec.rb
See Bugzilla bug #1102193 for reference.
To avoid confusion: When a repository is enabled or not, we talk about
zypper (RPM) repositories, which ship with a default, either `enabled`
or `disabled`. As an example, typically "debug symbols" are `disabled`
by default.
Before, if there were no `enabled` repositories for a product (which
happens for very old products), `mirror?` would return true even though
there was nothing mirrored. This kinda made sense since we accept a
__product__ as `enabled` when all the __repos__ that are `enabled` by
default are "enabled for mirroring", because that's usually everything
one needs (by definition, since they other repos on the clients are
`disabled` by default anyway).
Now it will first check if there are repositories that are `enabled` by
default. And …
> Fix products wrongly showing as enabled for mirroring

- features/lockfile_spec.rb
- lib/rmt/lockfile.rb
- package/rmt-server.changes
- spec/lib/rmt/lockfile_spec.rb
If the old PID has more digits than the current one user would see the wrong PID because the file is not truncated but only first digits are rewritten. This PR fixes that.
See also https://apidock.com/ruby/File/flock for an example.
The fix can be verified by writing some content into `/tmp/rmt.lock` which should be longer that the PID and then running 2 RMT CLI processes in 2 console tabs. You should see correct PID in the error message.
> Truncate PID in lockfile

- package/rmt-server.changes
- package/rmt-server.spec
Fixes following warnings from OBS which makes SR to be declined:
* Attention, http-certs.conf is not mentioned in spec files as source or patch.
* A Patch (use-ruby-2.5-in-rmt-data-import.patch) is being deleted without this removal being referenced in the changelog.
* A Patch (use-ruby-2.5-in-rmt-cli.patch) is being deleted without this removal being referenced in the changelog.
* A Patch (use-ruby-2.5-in-rails.patch) is being deleted without this removal being referenced in the changelog.
> Mention ruby-2.5 patches removal in changelog

- CHANGELOG
- lib/rmt.rb
- lib/rmt/mirror.rb
- package/rmt-server.changes
- package/rmt-server.spec
- spec/fixtures/vcr_cassettes/mirroring.yml
- spec/fixtures/vcr_cassettes/mirroring_with_auth_token.yml
Before, we used to always look for a "product.license" directory in the
repo's parent directory (i.e. "../product.license").
While most, if not all, SUSE-built repositories follow that convention,
it's not followed by all products.
The difference is that the directory is not always called
"product.license". In fact, the licenses are stored in repo_url +
".license", and it happens that the repo_urls built by SUSE end in
"product", so the licenses are in "product.license".
In the case of the IBM DLPAR Utils and IBM DLPAR SDK modules, the repos
end in "ppc64le", so the licenses are stored in directory named
"ppc64le.license".
> Fix license mirroring issue

- CHANGELOG
Unfortunately, GitHub doesn't redirect to the linked file, so it defeats
the purpose.
> Remove top-level link to changes file

- app/models/migration_engine.rb
- lib/rmt.rb
- package/rmt-server.changes
- package/rmt-server.spec
- spec/models/migration_engine_spec.rb
Verification: 
`curl -u '<SYSTEM_LOGIN>:<SYSTEM_PASSWORD>' -H "Content-type: application/json" -d '{ "installed_products": [ { "identifier": "SLES", "version": "15", "arch": "x86_64" } ] }' -X POST <YOUR_SCC_HOST>/connect/systems/products/migrations`
> Include Python2 module into SLE15 online migrations

- .simplecov
- config/application.rb
- lib/tasks/test.rake
Currently, if rspec fails, we continue on and give an exit code of 0, that shouldn't happen.
I split the code coverage into their respective code suites: core and engine. Core will fail if we're missing 100% code coverage in normal RMT and engine will fail if the engine files are not 100% tested.
> Rake test should fail on error

- lib/rmt/cli/base.rb
Usage: "rmt-cli mirror"
instead of
Usage: "rmt-cli \b mirror"
Fixes #363
> Fix \b in help text from incorrect commands

- lib/rmt/mirror.rb
- spec/lib/rmt/mirror_spec.rb
To [un-confuse the translators](https://l10n.opensuse.org/translate/rmt/i18n/ru/?type=comments#comments), also `suma` is not a proper way to reference SUSE Manager.
> Use proper product name of SUSE Manager

- config/initializers/fast_gettext.rb
- lib/rmt/cli/decorators/product_decorator.rb
This should enable adding hints for the translators for strings in the code. Only comments with a tag will show in `.po`/`.pot` files, I've set the tag to `i18n`.
Before:
```
msgid "Arch"
msgstr ""
```
After:
```
#. i18n: architecture
#: ../lib/rmt/cli/decorators/product_decorator.rb:39
msgid "Arch"
msgstr ""
```
The comments should show in Weblate.
> Enable comments for i18n strings

- integration/run.sh
Some files have been moved from `package` to `package/obs/` directory and that requires a small updated in integration tests script.
> Adapt integration tests to new RPM specfile

- README.md
- lib/suse/connect/api.rb
- spec/suse/connect/api_spec.rb
Added a check to only read the uuid-file if it is not empty, otherwise it creates a new uuid.
(... and added a dependency to readme)
> Create UUID when system_uuid file empty

- lib/rmt/cli/base.rb
- spec/lib/rmt/cli/main_spec.rb
- replaced "systemctl start rmt-migration" with "systemctl start rmt-server-migration.service" (see [bug](https://bugzilla.suse.com/show_bug.cgi?id=1136165))
> replaced string "rmt-migration" with "rmt-server-migration.service"

- lib/rmt/cli/main.rb
There's a forgotten alias left over from refactoring in #423, which shows up as an alternative for `rmt-cli r`.
> Remove refactoring leftover

- Gemfile.lock
* update fuubar, to 2.4.1 because 2.4.0 was removed from Rubygems
* update yard to 0.9.20 because of security alert GHSA-xfhh-rx56-rxcr
Because we don't use yard server (yard is a dependency of versionist) we do not need to create a changelog here.
> Update fuubar and yard gems

- lib/rmt.rb
- lib/rmt/downloader.rb
- lib/rmt/http_request.rb
- lib/rmt/mirror.rb
- package/obs/rmt-server.changes
- package/obs/rmt-server.spec
- spec/fixtures/vcr_cassettes/mirroring.yml
- spec/fixtures/vcr_cassettes/mirroring_with_auth_token.yml
- spec/lib/rmt/downloader_spec.rb
- spec/lib/rmt/mirror_spec.rb
Makes mirroring faster by downloading everything in parallel, especially when there are no pending .rpm/.drpm updates. On an RMT that didn't have any pending updates in 8 repos:
Before:
```
> time rmt-cli mirror
real	0m38.995s
```
After:
```
> time rmt-cli mirror
real	0m20.302s
```
1. License files: there's a lot of license files which were downloaded sequentially, e.g.:
```
license.de.txt
license.es.txt
license.fr.txt
license.it.txt
license.ja.txt
license.ko.txt
license.pt_BR.txt
license.ru.txt
license.txt
license.zh_CN.txt
license.zh_TW.txt
```
2. Metadata files: there's also a lot of them, also downloaded sequentially, e.g.:
```
a5b9125090f4487980e3bf94d469ae3a3c5c6e47016b18a0ddf26e9a7106bce7-susedata.cs.xml.gz
a5b9125090f4487980e3bf94d469ae3a3c5c6e47016b18a0ddf26e9a7106bce7-susedata.de …
```
> Faster mirroring / fix mirroring logic

- lib/rmt.rb
- package/files/nginx-pubcloud/nginx-https.conf
- package/obs/rmt-server.changes
- package/obs/rmt-server.spec
* Proxy only the known routes (`/connect`, `/service`, `/api` and `/repo/repoindex.xml`) to the backend. Currently everything gets proxied, so there's a lot of clutter in `journald` when a scanner hits a bunch of non-existent URLs, e.g.:
```
Jul 16 01:33:30 rmt-xxxxxxxxxxxxxx rails[1241]: FATAL: ActionController::RoutingError (No route matches [GET] "/moin_static182/modern/css/print.css"):
Jul 16 01:33:30 rmt-xxxxxxxxxxxxxx rails[1241]: FATAL:
Jul 16 01:33:30 rmt-xxxxxxxxxxxxxx rails[1241]: FATAL: actionpack (5.1.6.2) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
```
* Disable logging of not found errors for `/repo` with `log_not_found off`. Zypper doesn't know the format of the repo, so it always tries to get `media.1/media`, which creates a lot of clutter in nginx's …
> Improve nginx PubCloud configs

- app/models/product.rb
- db/migrate/20190717114051_remove_friendly_name_from_products.rb
- db/schema.rb
- lib/rmt.rb
- package/obs/rmt-server.changes
- package/obs/rmt-server.spec
- spec/factories/products.rb
- spec/models/product_spec.rb
- spec/serializers/v3/product_serializer_spec.rb
glue adds the release_stage to the friendly_name. This will now be removed while importing to rmt.
> Migration target display with RMT contains release stage

- package/files/nginx-pubcloud/nginx-http.conf
- package/obs/rmt-server.changes
Redirect to HTTPS is off and `@rmt_app` location is missing.
> Fix plain HTTP PubCloud config

- .gitignore
- PACKAGE.md
- app/controllers/api/connect/v4/repositories/installer_controller.rb
- lib/rmt.rb
- package/obs/rmt-server.changes
- package/obs/rmt-server.spec
- spec/factories/products.rb
- spec/lib/rmt/cli/products_spec.rb
- spec/requests/api/connect/v4/repositories/installer_controller_spec.rb
Some older versions of Yast in SLE12 seem to send an empty string for release_type. This
makes RMT fail with 'no product found'. This commit aligns RMT with the behavior of SCC,
and fixes the usage with SLE12 Yast.
> convert empty release type to nil.

- lib/rmt.rb
- lib/rmt/cli/main.rb
- lib/rmt/config.rb
- package/obs/rmt-server.changes
- package/obs/rmt-server.spec
- spec/lib/rmt/config_spec.rb
We took and documented the configuration value, but never actually used it.
> Fix mirror_src config

- engines/strict_authentication/app/controllers/strict_authentication/authentication_controller.rb
- engines/strict_authentication/spec/requests/strict_authentication/authentication_controller_spec.rb
- package/obs/rmt-server.changes
Allows access to repos that were not yet activated in order to allow for SLES11 systems to be migrated.
> PubCloud: allow access to SLES 12 SP1 repos when SLES 11 was activated

- engines/strict_authentication/app/controllers/strict_authentication/authentication_controller.rb
- engines/strict_authentication/spec/requests/strict_authentication/authentication_controller_spec.rb
- lib/rmt.rb
- package/obs/rmt-server.changes
- package/obs/rmt-server.spec
`/repo/$RCE/SLES11-SP4-Pool/sle-11-x86_64/` -- SLES 9 strikes back (dollar sign breaks the regex) :man_facepalming:
> Escape path in regex

- package/files/rmt-cli_bash-completion.sh
This adds the following completions:
`rmt-cli system`
`rmt-cli systems`
`rmt-cli systems help`
`rmt-cli systems list`
including flags: `--csv, --all, --limit=`
`rmt-cli systems scc-sync`
This fixes #513.
This also adds a missing parameter to the aliased function calls, which
prevented aliases to be completed correctly.
Have I missed any sub command? My installation doesn't have `scc-sync`yet, for example.
Please also test and review :)
> Add: bash-completion for 'systems' subcommand

- app/models/migration_engine.rb
- app/models/product.rb
- lib/rmt.rb
- package/obs/rmt-server.changes
- package/obs/rmt-server.spec
- fix offline migration
- Add changelog for signature file download for custom repositories
Resolving version bump conflict. Increased version of https://github.com/SUSE/rmt/pull/519 to 2.5.3 instead of 2.5.2.
Included changes from rmt_embargo.
> Fix offline migration

- README.md
- app/models/subscription.rb
- db/migrate/20200403075822_migrate_provisional_to_evaluation.rb
- db/schema.rb
- lib/rmt.rb
- package/obs/rmt-server.changes
- package/obs/rmt-server.spec
This pull request  aligns the subscriptions kinds with scc.suse.com. SCC has removed the `provisional` type and added a new `partner` type for partner subscriptions.
belongs to:  https://trello.com/c/t9Hb2nLE/1291-sh-align-subscription-types-kinds-with-scc
> Fix subscription kinds

- features/lockfile_spec.rb
- lib/rmt.rb
- lib/rmt/cli/mirror.rb
- lib/rmt/http_request.rb
- lib/rmt/lockfile.rb
- package/obs/rmt-server.changes
- package/obs/rmt-server.spec
- spec/lib/rmt/lockfile_spec.rb
- spec/spec_helper.rb
- spec/support/shared_examples/cli.rb
Does 3 things:
* Fixes the lockfile bug (bsc#1165548) -- creates locks in the DB instead of /tmp;
* Addresses concerns that were raised with regards to containerization of RMT -- having locks in the DB prevents different containers from running the same task;
* Creates separate locks for sync/import and mirror jobs -- mirror job doesn't really conflict with a sync/import job (as it only reads from the DB); this should fix an issue we often have -- mirror jobs run over 24 hours in some regions, sync jobs break due to lockfiles being held by those long-running mirror jobs.
> Lockfile overhaul

- package/obs/rmt-server.changes
- package/obs/rmt-server.spec
Some of the rmt-server RPM package's dependencies (mariadb and nginx) are marked as required, but they aren't really required to run, rmt-server, especially for containerized usage.
This PR marks these packages as recommended and makes some other package adjustments.
> Fix RPM dependencies packages

- package/files/nginx-pubcloud/nginx-http.conf
- package/files/nginx-pubcloud/nginx-https.conf
We've had some changes made to the configs to support old SLE11 clients, now that SLE11 is out of support we can revert those changes.
> rmt-server-pubcloud: SLE11 EOL

- package/obs/rmt-server.changes
- package/obs/rmt-server.spec
"The posttrans in the spec file reloads nginx for the main package, but the nginx configuration is in sub-packages. So if a configuration sub-package without nginx config is installed, this leads to a systemctl/RPM error."
Replaces pull request https://github.com/SUSE/rmt/pull/575 (deleted forked repo)
Reviewed there by 
lcaparroz and ikapelyukhin
> Move reloading of nginx to correct sub-packages

- app/models/downloaded_file.rb
- db/migrate/20200723124836_add_uniqueness_to_downloaded_files_local_path.rb
- db/schema.rb
- lib/rmt/deduplicator.rb
- lib/rmt/downloader.rb
- lib/rmt/file_validator.rb
- lib/rmt/mirror.rb
- spec/lib/rmt/deduplicator_spec.rb
- spec/lib/rmt/downloader_spec.rb
- spec/lib/rmt/file_validator_spec.rb
- spec/lib/rmt/mirror_spec.rb
- spec/models/downloaded_file_spec.rb
- spec/support/deduplication_helpers.rb
@ikapelyukhin pointed out some issues on PR #585, which should be addressed in order to assure data integrity on the customer database without affecting the mirroring process performance.
* `DownloadedFile#local_path` uniqueness: I created a new migration which will remove possible duplicated `local_path` entries, if any, prior to adding an index with an uniqueness constraint to the field.
* I removed all local file validation logic from `DownloadedFile` and `RMT::Deduplicator`: now, all validation and data integrity logic is on `RMT::FileValidator`, which also fix invalid DB entries when searching for a  candidate source file for deduplication.
* Right now, file validation before deduplicating/downloading works without changes: `RMT::FileValidator` has an option for "deep verifying," …
> Downloaded data integrity improvement

- MANUAL.md
- lib/rmt/cli/repos.rb
- lib/rmt/cli/repos_custom.rb
- lib/tasks/encrypted_key.rake
- spec/factories/repositories.rb
- spec/lib/rmt/cli/repos_custom_spec.rb
- spec/lib/rmt/cli/repos_spec.rb
- spec/support/deduplication_helpers.rb
- spec/support/downloaded_files.rb
We did not give users the ability to remove unused repositories. To fix this, we created a command to delete repository directories which aren't marked to be mirrored.
> Add the ability to remove un-mirrored repositories

- README.md
- docs/SECURITY.md
Let's avoid users creating security issues in github and instead point
them to the SUSE Security Team.
> Added a starting Security Policy

- app/controllers/api/connect/v3/systems/products_controller.rb
- app/controllers/api/connect/v4/repositories/installer_controller.rb
- app/models/repository.rb
- lib/rmt.rb
- lib/rmt/cli/export.rb
- lib/rmt/cli/repos.rb
- package/obs/rmt-server.changes
- package/obs/rmt-server.spec
- spec/factories/activations.rb
- spec/factories/services.rb
- spec/lib/rmt/cli/products_spec.rb
- spec/models/repository_spec.rb
When we checked if a product was mirrored for product activation, we only verified that a product was enabled for mirroring. Instead, let's check if RMT mirrored that product at least once with last_mirrored_at.
> Check if fully mirrored before activating product

- features/repos_spec.rb
Because we've enabled the installer updates repository, we have more repositories in our list than before. If we don't remove them from the list with grep, the list will grow with every newly released product and break our tests.
> Fix integration tests

- MANUAL.md
- app/models/repository.rb
- app/services/repository_service.rb
- db/migrate/20200916104804_make_scc_id_unique.rb
- db/migrate/20200916120607_add_friendly_target_to_repositories.rb
- db/schema.rb
- lib/rmt.rb
- lib/rmt/cli/decorators/custom_repository_decorator.rb
- lib/rmt/cli/decorators/repository_decorator.rb
- lib/rmt/cli/mirror.rb
- lib/rmt/cli/repos.rb
- lib/rmt/cli/repos_base.rb
- lib/rmt/cli/repos_custom.rb
- lib/rmt/cli/smt_importer.rb
- package/obs/rmt-server.changes
- package/obs/rmt-server.spec
- spec/factories/repositories.rb
- spec/lib/rmt/cli/mirror_spec.rb
- spec/lib/rmt/cli/products_spec.rb
- spec/lib/rmt/cli/repos_custom_spec.rb
- spec/lib/rmt/cli/repos_spec.rb
- spec/lib/rmt/cli/smt_importer_spec.rb
- spec/lib/rmt/scc_spec.rb
- spec/services/repository_service_spec.rb
The code assumes scc_id is unique, and under normal circumstances, scc_id should always be unique, but the database didn't ensure this (non-unique index).
Note:
* For duplicated scc_ids, we remove the scc_id column, making it null. The next sync to SCC will bring the duplicated repository to a healthy state and set the scc_id to the correct repository.
Instead of using two columns for IDs, we should use one to lower the confusion. This PR adds the column `friendly_id`. For SCC repositories, it's the same `scc_id` as before. For custom repositories, it's either user provided or RMT generated (MD5 checksum of URL).
**Note:**
* `scc_id` was left for backwards compatibility reasons and to determine whether or not a repository comes from SCC.
* Custom repositories can use the old `id` within …
> Have a Singular Id for SCC and Custom Repositories

- integration/prophet/prophet.rb
Github is deprecating usage of its API by password authentication, so we need to move to token authentication.
> Move to GH Tokens for Prophet

- lib/rmt.rb
- lib/rmt/cli/base.rb
- lib/rmt/cli/export.rb
- lib/rmt/cli/import.rb
- package/obs/rmt-server.changes
- package/obs/rmt-server.spec
- spec/lib/rmt/cli/export_spec.rb
- spec/lib/rmt/cli/import_spec.rb
We didn't expand relative paths before, and this mostly worked, but it caused an issue with `rmt-cli import repos`. This is because RMT tried to build URIs from a relative path like "./test" to "file://./test", which is wrong.
> Expand Input Paths

- lib/rmt/downloader.rb
- lib/rmt/mirror.rb
- lib/rmt/mirror/file_reference.rb
- spec/lib/rmt/downloader_spec.rb
- spec/lib/rmt/mirror/file_reference_spec.rb
- spec/lib/rmt/mirror_spec.rb
I refactored the classes `RMT::Mirror` and `RMT::Downloader` to improve how they communicate with each other, focusing on making `RMT::Downloader` to only accept instances of `RMT::Mirror::FileReference`.
The RMT::Downloader had a public interface which was quite complex:
* A new instance was initialized with parameters that could be modified later by an external agent: repository URL, and repository and cache directories. `RMT::Mirror` creates a `RMT::Downloader` instance during initialization and then modifies these attributes whenever it wants to download a different set of files, so it was hard to know, at any given point, what was the downloader configuration/state. These parameters were used solely for building URLs and paths for the downloaded files.
* RMT::Downloder public methods …
> Refactor RMT Mirror Downloader

- lib/rmt.rb
- lib/rmt/cli/import.rb
- lib/rmt/downloader.rb
- lib/rmt/fiber_request.rb
- lib/rmt/mirror/file_reference.rb
- package/obs/rmt-server.changes
- package/obs/rmt-server.spec
- spec/fixtures/vcr_cassettes/mirroring_product_with_cached_metadata.yml
- spec/lib/rmt/downloader_spec.rb
- spec/lib/rmt/mirror/file_reference_spec.rb
- spec/lib/rmt/mirror_spec.rb
`RMT::Downloader` decided whether to download a file or copy it from cache based on a combination of the file timestamp and the HTTP header `'If-Modified-Since'`: if the file timestamp on disk is newer than on
server, the HTTP response code would be 304 (not modified).
This caused some unexpected behavior if, accidentally, the file timestamp on disk changed. The timeline example below better illustrates the bug:
1. The first time 'repomd.xml' is downloaded from a repo, its `mtime` attribute on the RMT server is correct, since it's been just created;
2. A new version of 'repomd.xml' has been released and is available for mirroring;
3. Accidentally, the file's `mtime` on the RMT server changed to a time newer than the new 'repomd.xml' timestamp on the repo;
4. The next time RMT server tries …
> Fix RMT::Downloader cache mechanism

- MANUAL.md
- app/models/repository.rb
- app/services/repository_service.rb
- db/migrate/20200916120607_add_friendly_target_to_repositories.rb
- lib/rmt.rb
- lib/rmt/cli/repos_custom.rb
- lib/rmt/cli/smt_importer.rb
- package/obs/rmt-server.changes
- package/obs/rmt-server.spec
- spec/lib/rmt/cli/repos_custom_spec.rb
- spec/models/repository_spec.rb
In the demo of the friendly_id feature, the MD5 of URLs was seen as not as user friendly. This is an attempt to use name instead.
> Use name to build friendly_ids for custom repos

- app/services/repository_service.rb
- lib/rmt/cli/repos_custom.rb
- spec/services/repository_service_spec.rb
If SCC repositories changed their URLs, RMT had issues. This is because we expect scc_id to be unique, and with a new URL, it tries to create a new repository with the same scc_id. Instead of finding by the URL for SCC repositories, we can find by scc_id instead and avoid this issue.
> Protect Against Changing SCC Repo URLs

- lib/rmt/cli/repos.rb
- spec/lib/rmt/cli/repos_spec.rb
When using the repos clean command it is a bit more helpful to output the currently running deletion like:
```
Deleting locally mirrored files from repository 'SLE-Module-Containers12-Pool for sle-12-x86_64'...
```
Especially when it takes longer because it's a large repo, it indicates that the process is still running.
Fixes #661
> Show what it's "Deleting..." instead of what was "Deleted"

- lib/rmt/cli/base.rb
- spec/lib/rmt/cli/main_spec.rb
The `/organization` route in SCC doesn't exist anymore.
Also we should avoid linking to specific routes as they might change.
Linking to just SCC should be enough to guide the user where the credentials can be found.
Trivial update of CLI output.
- Blank your `scc` credentials in your local config file.
- I think this change is trivial enough to not require a changelog update. Do you agree?
> Replace outdated deeplink with link to SCC landing URL

- integration/Dockerfile.test
- integration/install.sh
Since December 2020, SLES15 GA images have been discontinued. The test pipeline uses these images and pipelines have been broken. This PR updates the integration test image.
Related Card: https://trello.com/c/0ZhhKlKD/1803-rmt-update-docker-image-for-integration-tests
> Fix test image issues

- .bundle/config_packaging
- .gitignore
- package/obs/rmt-server.spec
The latest Nokogiri which includes native binaries broke the build on non-x86 platforms.
> Enforce packing Rubygems in platform agnostic way

- Gemfile
- app/models/migration_engine.rb
- package/obs/rmt-server.changes
- spec/models/migration_engine_spec.rb
- spec/requests/api/connect/v3/systems/products_controller_spec.rb
This makes https://github.com/SUSE/happy-customer/pull/5256 available for RMT.
> Raise an exception when there is an extension activated which has no migration successor

- app/models/migration_engine.rb
- spec/models/migration_engine_spec.rb
- spec/requests/api/connect/v3/systems/products_controller_spec.rb
Improve migration error message with uninstall command, 
only raise error when extensions have no successor. 
A base without successor is expected, ie. latest product like SLES 15 SP3.
Fixes https://trello.com/c/r6zomyoz/1652-raise-error-message-in-migration-when-there-is-no-successor
- [x **Bug Fix** (a non-breaking change which fixes an issue)
> Improve migration error message with uninstall command

- lib/rmt.rb
- lib/rmt/cli/repos_base.rb
- package/obs/rmt-server.changes
- package/obs/rmt-server.spec
- spec/lib/rmt/cli/repos_custom_spec.rb
card: https://trello.com/c/ReYjExvX/1866-rmt-fix-management-of-custom-repositories
bug: https://bugzilla.suse.com/show_bug.cgi?id=1182736
This is a bug occuring if the first characters of an ID are numbers e.g `15ptf-repo`. In `ActiveRecord` the `find_by` searches for the numeric id and strings automatically translated to an integer and trailing characters get truncated. This results in odd behaviour.
* How to test the change:
```
1) bin/rmt-cli repos custom add "https://download.opensuse.org/repositories/server:/http/SLE_15/" 15sp1-basesystem-ptf
2) bin/rmt-cli repos custom list
3) bin/rmt-cli repos custom remove 15sp1-basesystem-ptf
4) bin/rmt-cli repos custom list
```
❤️ Thank you! ❤️
> Add check for numeric ids to not convert strings into numbers

- lib/rmt/cli/repos_custom.rb
- package/obs/rmt-server.changes
- spec/lib/rmt/cli/repos_custom_spec.rb
Fixes slash at the end of custom repo urls.
1. Add a custom repo with url query like `bin/rmt-cli repos custom add http://example.com?token`
2. List the custom repos with `bin/rmt-cli repos custom list`. The url should have the token without a trailing slash.
> Fix appended slash when query is present in custom repo url

- package/obs/rmt-server.spec
Dropping the Gemfile.lock 'BUNDLED WITH' line during build.
This caused issues when the distribution already has Bundler >=2 and 
the Gemfile.lock was created with Bundler 1.x
> Dropping the Gemfile.lock 'BUNDLED WITH' line during build

- config/environments/production.rb
This PR fixes Rails 6.1 autoloading which is breaking rmt server startup. Here's a [PR on the rails repo](https://github.com/rails/rails/issues/40904)
1. Run the production server with `bundle exec rails s -e production`
Server should start with no issues.
> Fix rails 6.1 autoloading

- .github/workflows/integrations.yml
`Danger` doesn't use the repo github token when a PR is opened from a fork. This will temporarily disable checks for `Danger`.
> Disable danger on forks

- lib/rmt/mirror/file_reference.rb
- package/obs/rmt-server.changes
- spec/lib/rmt/mirror/file_reference_spec.rb
card: https://trello.com/c/L5XhKiBw/2089-rmt-l3-mirroring-packages-with-special-characters-in-the-url-fails
bug: https://bugzilla.suse.com/show_bug.cgi?id=1189805
RMT does not handle non URI RFC3986 characters in package names correctly. By adding URI encoding to the package name RMT is able to handle complex package names as well.
You need a running development setup of RMT and some disk space to run a mirror on the epel repository.
```
$ git checkout master
$ bin/rmt-cli repos custom add "http://mirrors.kernel.org/fedora-epel/8/Everything/x86_64/" epel-8-everything
$ bin/rmt-cli mirror repository epel-8-everything
$ git checkout handle-special-characters
$ bin/rmt-cli mirror repository …
```
> Handle special characters in package names (bsc#1189805)

- package/obs/rmt-server.changes
This PR attempts to fix the wording on our changelog. It further clarifies what is being deployed with version`2.6.12`.
> Update changelog wording for 2.6.12 release

- bin/rmt-cli
- lib/rmt.rb
- lib/rmt/config.rb
- lib/suse/connect/api.rb
- spec/lib/rmt/config_spec.rb
- spec/suse/connect/api_spec.rb
If possible, try to pass the host's login information into a new header. This header will be handled by glue so to link this registration proxy with the its registered host.
If the host is not registered into SCC, nothing will happen and it will work as usual. If the host is registered but the credentials file is not readable by the running user, a warning will be printed, but everything will run as usual.
**To be done**: add tests. I've been told to first have a discussion on the implementation details.
> api: try to also pass the host login information to glue

- lib/suse/connect/api.rb
- spec/lib/suse/connect/api_spec.rb
This pull request adds the `regcode` attributes to `product` attributes in the
`POST $host/organizations/systems` call.
This allows SCC to consume which product was activated by which subscriptions.
**Note: This is depended on https://github.com/SUSE/rmt/pull/789 which is why all changes from #789 are listed here as well**
tbd
> Send subscriptions associated to a product on system activation to Glue

- db/migrate/20220113074644_remove_products_negative_id.rb
- package/obs/rmt-server.changes
Purge products with a negative ID if they are on the database.
In order to test it, make sure that you have products with a negative ID (e.g. by calling `sync` before applying this patch). After applying this, you should be able to call `sync` and check that there are no products with a negative ID.
> sync: purge products with a negative id

- lib/suse/connect/api.rb
- spec/lib/suse/connect/api_spec.rb
- spec/requests/api/connect/v3/systems/activations_controller_spec.rb
This will not happen if, for example, the only change is on the `last_seen_at` column an nothing else.
This change is related to report more consistent data to SCC.
> Send last_seen_at column when syncing systems

- lib/rmt/mirror/file_reference.rb
Commit 8f68994ca6a352031261199a1dead5f27ddffe10 added encoding of file names so that special characters are properly escaped when handled over network. However, it does so also for files stored locally on the filesystem, which leads to `rmt-cli import` failing due to the expected (encoded) file names not existing. This patch prevents encoding for files that are handled through the `file://` scheme.
Fixes bsc#1195201
> Do not encode file that are imported from the filesystem (bsc#1195201)

- MANUAL.md
- lib/rmt/cli/systems.rb
- spec/lib/rmt/cli/systems_spec.rb
This command allows users to delete inactive systems. By default, inactive systems are those which have not contacted RMT for at least 3 months.
Setup an RMT instance with a variety of systems on it. Tweak the `last_seen_at` attribute of these systems according to your testing purposes. Then, check that `rmt-cli systems purge` lists you first the systems that will get deleted and that you need to confirm for this to actually happen. Check that you can bypass this question by calling this command with the `--non-interactive` flag. Finally, check that you can change which systems are to be picked with the `--before` flag, which expects a string with the format `<year>-<month>-<day>` (even though any date format would actually work).
*Please check off each …
> cli: added the 'systems purge' command

- lib/rmt/cli/decorators/system_decorator.rb
The command `rmt-cli systems list --csv` had an issue with its output, where the value in the column "Products" was presented as a list of items separated by new line characters. This is counter-intuitive since one expects a CSV file to have just one entry per line.
This commit fix the behavior by separating the items in the "Products" columns by spaces.
> Fix `systems list` CSV output

- lib/rmt.rb
- lib/rmt/scc.rb
- lib/suse/connect/api.rb
- package/files/systemd/rmt-server-mirror.timer
- package/files/systemd/rmt-server-sync.timer
- package/files/systemd/rmt-server-systems-scc-sync.timer
- package/obs/rmt-server.changes
- package/obs/rmt-server.spec
- spec/factories/systems.rb
- spec/lib/rmt/scc_spec.rb
- spec/lib/suse/connect/api_spec.rb
- Refactor API call function to yield results
- Use bulk send API for SCC system update
- Remove system forwarding logic
- Running RMT checkout out to `use_bulk_send_api_for_system_sync` branch
- Connection to SCC working (e.g. `rmt-cli sync` works)
- Mirroring at least one SLES and HA (in this howto it is 15.3)
- A running 15.3 container (e.g. from SUSEConnect repository)
```bash
$  = rmt host terminal
>  = SLES docker container
% = rmt host rails console
!  = expectation
! Make sure RMT is running (assuming http://localhost:4224)
```
---
**Show that a newly registered system behind RMT gets fully synced to SCC in the daily sync process**
```bash
$ docker run --rm --network=host -h review-1 --network=host -ti connect.15sp3 /bin/bash
> SUSEConnect -r <slesregcode> --url …
```
> Use bulk send api for system sync

- MANUAL.md
- lib/rmt/cli/repos.rb
- lib/rmt/cli/systems.rb
- spec/lib/rmt/cli/repos_spec.rb
- spec/lib/rmt/cli/systems_spec.rb
Instead of using multiple switches for `non interactive`/`no confirmation` in `rmt-cli`, streamline them to `-no-confirmation`.
Note: Since thor is automatically adding positive and negative switches when using a `boolean` switch all these commands
come now with: `--confirmation` and `--no-confirmation`.
Before they where like `--non-interactive` and `-no-non-interactive`.
```bash
$ = rmt host terminal
!  = expectation
```
```bash
$ rmt-cli systems purge --help
! --no-confirmation should be available and described
$ rmt-cli systems purge --before 2022-02-02
! Should ask you if you want to delete systems
$ rmt-cli systems purge --no-confirmation --before 2022-02-02
! Should purge the systems without user interaction
```
---
```bash
$ rmt-cli repos clean --help
! --no-confirmation should be …
```
> Move to --no-confirmation for all non interactive modes in rmt-cli

- .github/workflows/integrations.yml
- .rubocop_todo.yml
- .simplecov
- Gemfile
- Gemfile.lock
- lib/rmt.rb
- lib/rmt/cli/base.rb
- lib/rmt/db.rb
- lib/rmt/downloader.rb
- lib/rmt/downloader/exception.rb
- lib/rmt/gpg.rb
- lib/rmt/http_request.rb
- lib/rmt/mirror.rb
- lib/rmt/scc.rb
- lib/suse/connect/api.rb
- package/obs/rmt-server.changes
- package/obs/rmt-server.spec
- spec/lib/rmt/cli/main_spec.rb
- spec/lib/rmt/cli/systems_spec.rb
- spec/lib/rmt/downloader_spec.rb
- spec/lib/rmt/mirror_spec.rb
- spec/rails_helper.rb
The `Downloader` class is handling the download logic, so it's the logical place 
to own also the retry logic. 
The retries can be tested with: 
```
sudo tc qdisc add dev em1 root netem loss 50%
bin/rmt-cli mirror
sudo tc qdisc del dev em1 root netem loss 50%
```
> Moving the retry logic of failed download requests to the `Downloader` class.

- lib/suse/connect/api.rb
- spec/lib/suse/connect/api_spec.rb
Send the `system.id` if the system is using a `system_token` in RMT. This ensures we get a unique system on SCC even if we do not send the *actual* `system_token`.
**Preparation**:
You need:
- A running SCC instance (glue)
- A RMT environment configured to use the local SCC instance (rmt.conf + mirroring credentials)
- RMT has SLES15SP3 and SLES15GA products enabled and mirrored
- Docker to run multiple SLES15SP3 and SLES15GA containers
- A regcode from the organization you configured RMT (aka <regcode>)
**Review:**
legend:
```
$ = host system
> = docker container
>> = RMT rails console (bin/rails c)
#! = expectation
```
```
$ bin/rmt-cli sync
$ bin/rails s
$ docker run --privileged --rm -h forward-id-1 --network=host -ti connect.15sp3 /bin/bash
> SUSEConnect -r <regcode> --url …
```
> Send system_token (actually the system id) if available

- lib/suse/connect/api.rb
- lib/suse/connect/system_serializer.rb
- package/obs/rmt-server.changes
- spec/lib/suse/connect/api_spec.rb
- spec/lib/suse/connect/system_serializer_spec.rb
Adding `system.created_at` and `activation.created_at` to the SCC API calls to make possible for SCC to better detect system creation and product activation dates.
part of: https://trello.com/c/7YwvJ3NN/2546-uras-track-actual-system-creation-and-product-activation-times
This pull request is also a refactoring of the `api_spec.rb` test file. It additionally adds `SystemSerializer` to serialize a `system` into the required attributes we send to SCC.
**How to review this pull request?**
Since this a feature + refactoring this pull request is best reviewed in `commits`. I tried to first implement the new behavior (serializer_ and continued to first update the existing tests and made sure the current implementation is still green on the changed tests. Afterwards exchanged the behavior of the …
> Send system creation date and product activation date.

- public/tools/rmt-client-setup-res
On RHEL9 rhel-release is protected, so it cannot be updated to sll-release.
This patch fixes this problem.
- [ x ] **Bug Fix** (a non-breaking change which fixes an issue)
- [ x ] I have reviewed my own code and believe that it's ready for an external review.
- [ x ] I have provided comments for any hard-to-understand code.
- [ x ] RMT's test coverage remains at 100%.
- [ x ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.
Change is trivial no need to document it in changelog.
> sll-release cannot be installed because rhel-release is protected on rhel9.

- public/tools/rmt-client-setup-res
add suseconnect.timer for sll9 and higher.
remove --yes switch, because it is not supported with rmt-client-setup script.
Script fails with --yes, so I guess noone use it. 
I consider these changes trivial, so I do not document them in changes file.
- [ x ] **Bug Fix** (a non-breaking change which fixes an issue)
- [ x ] I have reviewed my own code and believe that it's ready for an external review.
- [ x ] I have provided comments for any hard-to-understand code.
- [ x ] RMT's test coverage remains at 100%.
- [ x ] If my changes are non-trivial, I have added a changelog entry to notify users at …
> set suseconnect.timers for sll version >= 9

- app/controllers/application_controller.rb
- app/controllers/services_controller.rb
Some systems might not use SUSEConnect ever again but still be active. Before this commit, we only assumed that systems using SUSEConnect from time to time were active, and we made sure about this with the optional service that runs `SUSEConnect --keepalive`.
That being said, refreshing services from zypper also contact RMT, and that's another point where `last_seen_at` can be updated as well. However, this was not going through the existing authentication workflow, and thus we could not figure out the system performing the action. But, as it turns out, Zypper will actually be able to follow the mechanism even if we add it now. This commit only adds this for Zypper, since we know that it already works and we want to keep backwards compatibility.
- [Trello …
> Update the last_seen_at column on service refresh

- .rubocop_todo.yml
- lib/rmt/downloader.rb
- lib/rmt/downloader/exception.rb
- package/obs/rmt-server.changes
- spec/lib/rmt/downloader_spec.rb
This affected the .license directory that always gets tried to load, but doesn't exist for many repos.
Reproduce by following https://documentation.suse.com/sles/15-SP1/html/SLES-all/cha-rmt-mirroring.html#sec-rmt-mirroring-export-import
and see .license directories immediately marked with: No license directory found for repository ...
> Do not retry to load non-existing files in "rmt-cli import repos"

- package/obs/rmt-server.changes
Lef tover from f9547b09ca57, in which I forgot to also update the changelog in our git repository.
> package: syncing the changelog with the one on OBS

- lib/rmt/mirror.rb
- package/obs/rmt-server.changes
- spec/lib/rmt/mirror_spec.rb
Adding -f to the file move command when moving the mirrored directory to its final location.
This fixes a problem with some filesystem setups, see bsc#1203171
> Adding -f to the file move command

- db/migrate/20200723124836_add_uniqueness_to_downloaded_files_local_path.rb
- db/migrate/20200916104804_make_scc_id_unique.rb
Our CI is broken due to:
Error: `no implicit conversion of Hash into String`
in: `db/migrate/20200723124836_add_uniqueness_to_downloaded_files_local_path.rb:5`
To fix this I removed the superflous translations using `_()`.
**How to test:**
- Check the code changes!
- Check that ruby 3.x github CI is green
> Remove translations from migration logging because it breaks in ruby 3.x

- Gemfile
- Gemfile.lock
- lib/rmt.rb
- package/obs/rmt-server.changes
- package/obs/rmt-server.spec
Activesupport has fixed a XSS in their code base due to missing detected for new string behavior in ruby 3.2. We are actually not affected by this. But to make sure we safe :rocket:
**How to test this code**:
- Grab the branch and make a `make dist`
- Copy the files to your obs repo for RMT and build the package. Make sure everything is fine
> Release 2.12 - Bump activesupport to fix CVE-2023-28120

- Gemfile
- Gemfile.lock
- package/obs/rmt-server.changes
... we updated the gem a while ago, now we have an official bug open for this. Here is the paperwork!
> Append to 1.12: Explicitly mark updated rack for CVE-2023-27530

- MANUAL.md
- lib/rmt.rb
- lib/rmt/cli/clean.rb
- lib/rmt/cli/main.rb
- package/obs/rmt-server.changes
- package/obs/rmt-server.spec
- spec/lib/rmt/cli/clean_spec.rb
- spec/support/cli_helpers.rb
- spec/support/shared_contexts/cli/clean.rb
- spec/support/shared_examples/cli/clean.rb
This PR proposes an implementation for an `rmt-cli clean packages` command, which allows RMT users to remove stale packages from disk and database entries referencing those files.
Fixes  #662, though not exactly described: instead of directly checking the SCC API for identifying stale files, it relies on locally mirrored metadata, which, indirectly, should reflect the data on SCC (if mirror service is enabled in the RMT host).
> Command for cleaning stales packages

- package/obs/rmt-server.changes
- public/tools/rmt-client-setup-res
symlink, but rpm expected directory.
in centos8 /usr/share/redhat-release is a symlink to centos-release. When register client to rmt, rpm tries to update centos-release.rpm to sll-release.rpm and fails because it cannot convert symlink to directory. Solution is to remove the file before register.
- [ x] **Bug Fix** (a non-breaking change which fixes an issue)
- [ x] I have provided comments for any hard-to-understand code.
- [ x] RMT's test coverage remains at 100%.
- [ x] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.
Please use …
> CentOS8 client cannot register to rpm

- package/obs/rmt-server.changes
Updated `rmt-server.changes` in preparation for rmt release.
> Update package changes file

- support/README.md
- support/rmt
ALP will not support the deprecated scplugin.rc framework. This commit, then, migrates our support script to work with supportconfig.rc.
This patch has been originally contributed by Jason Record on the linked Bugzilla entry.
Fixes bsc#1216389
**NOTE**: I have tested the following on a SLES15 SP4 machine. It would be extra dope if you could test it on other environments such as SLES12 LTSS.
The easiest route is to either install RMT on a machine, or re-use an existing installation. Thus, before any of this, ensure that `rmt-server` and `supportutils` are installed on your system. Then just copy the `support/rmt` file from this PR into `/usr/lib/supportconfig/plugins` and give it executable rights (as root):
```
```
To ensure that the installation works, run `supportconfig` like so:
``` …
```
> support: migrated to supportconfig.rc

- app/services/repository_service.rb
- lib/rmt/cli/repos_custom.rb
- lib/rmt/scc.rb
- lib/suse/connect/api.rb
- spec/lib/rmt/cli/repos_custom_spec.rb
- spec/lib/rmt/scc_spec.rb
> Update repo urls on sync from SCC

- lib/tasks/encrypted_key.rake
- package/files/update_rmt_app_dir_permissions.sh
- package/obs/rmt-server.changes
The problem is that the file permission where originally wrong and breaks RMT completely because it can not read the secrets. This fixes the permissions for both files without relying on handling this in the spec file where it should **not** be handled anyway.
original:
```
-rwxr-xr-x 1 root root  1277 Dec 12 05:42 /usr/share/rmt/config/secrets.yml
-rw-r--r-- 1 root nginx  280 Jan  2 13:52 /usr/share/rmt/config/secrets.yml.enc
-rw------- 1 root nginx   32 Jan  2 13:52 /usr/share/rmt/config/secrets.yml.key
```
but we need due to hardening:
```
-rwxr-xr-x 1 root root  1277 Dec 12 05:42 /usr/share/rmt/config/secrets.yml
-rw-r----- 1 root nginx  280 Jan  2 13:52 /usr/share/rmt/config/secrets.yml.enc
-rw-r----- 1 root nginx   32 Jan  2 13:52 /usr/share/rmt/config/secrets.yml.key
```
see: …
> Fix secrets file access mode - for real!

- Gemfile
- Gemfile.lock
- package/obs/rmt-server.changes
part of: https://trello.com/c/BfrlfQwR/3154-support-zst-compression-format-in-rmt
Also handles:  https://github.com/SUSE/rmt/pull/1045 and https://github.com/SUSE/rmt/pull/1042
fixes: https://github.com/SUSE/rmt/issues/1050
This is updating `repomd_parser` which now comes with zstd support and pinning gems which updates now requires `ruby 2.6+` to work.
**How to review this pull request:**
- Run `bundle` and see updates coming through
- Check `zstd` support:
```
$ bin/rmt-cli repos custom add http://download.opensuse.org/tumbleweed/repo/oss/ tumble-oss
$ bin/rmt-cli mirror repository tumble-oss
```
**Thank you for reviewing this pull request! If you have questions, please do not hesitate to ask!** :rocket:
> Bump repomd_parser to 0.1.6 for ztd and pin gems which have 2.6+ dependency on later versions

- app/controllers/services_controller.rb
- lib/rmt/misc.rb
- package/obs/rmt-server.changes
- spec/requests/services_controller_spec.rb
In normal RMT environments, zypper services do not need a ?credentials URL parameter since the repository path is not authenticated.
So do not add it and allow yum to work with RMT for SLL7
part of: https://trello.com/c/BSMxlGDN/3166-help-liberty-team-get-suseconnect-working-on-liberty-7
**How to review this pull request:**
```bash
$ cd <rmt>
$ git checkout no-credentials-in-service-url
$ rails server
$ docker run --rm -it --network=host registry.suse.com/suse/sle15:15.4
> zypper in -y suseconnect-ng curl tidy
> SUSEConnect --url http://localhost:4224
> cat /etc/zypp/credentials.d/SCCcredentials
> curl -u <username:password> http://localhost:4224/services/2292 | tidy -xml -iq 
```
**If you have any questions, please do not hesitate to reach out to me!** :rocket:
**Thank you!**
> Do not add service credential url paramter if not necessary

- db/migrate/20240129140413_remove_obsolete_res7_repositories.rb
part of: https://trello.com/c/BSMxlGDN/3166-help-liberty-team-get-suseconnect-working-on-liberty-7
This removes the old obsolete repositories, since RMT does not automatically remove them.
**How to test this change:**
- Find a RMT server which is running for some time now.
- Check if the server is affected by:
```
$ rails c
> Product.find(1251).repositories.pluck(:name,:scc_id,  :external_url)
```
- Run the migration:
```
$ rails db:migrate
$ rails c
> Product.find(1251).repositories.pluck(:name,:scc_id,  :external_url)
```
**As always, if you have question or suggestions, please do not hesitate to ask!**:rocket:
Thank you!
> Remove old RES7 repositories in a database migration

- package/obs/rmt-server.changes
We are almost there, just waiting for SLL7 script changes to release 2.15 finally!
The pre-release is for PCT/SRE to test the release early.
It is still missing SLL7 script changes.
> 2.15 Pre-release

- package/obs/rmt-server.spec
sqlite is missing as build requirement.
**How to review this pull request:**
- It builds in obs!
> Add missing build require for sqlite; the real pre-release

- engines/scc_proxy/lib/scc_proxy/engine.rb
- engines/zypper_auth/spec/requests/strict_authentication/authentication_controller_spec.rb
- package/obs/rmt-server.changes
When checking SCC for subscription expiration
on a GET request, SCC does rotate the system token
Set the byos info on the request to fix that
Update changelog to keep track of pub cloud changes
> Add BYOS info to SCC GET request

- engines/instance_verification/lib/instance_verification/engine.rb
- engines/instance_verification/spec/requests/api/connect/v3/systems/products_controller_spec.rb
- engines/scc_proxy/lib/scc_proxy/engine.rb
- engines/scc_proxy/spec/requests/api/connect/v3/systems/products_controller_spec.rb
- engines/zypper_auth/lib/zypper_auth/engine.rb
- package/obs/rmt-server.changes
Given the high number of re requests to SCC for BYOS systems to refresh the cache, extend the cache longer for BYOS systems
> Longer cache byos

- package/obs/rmt-server.changes
- public/tools/rmt-client-setup-res
Newest yum update released last week break our repository (cannot read repomd.xml)
(bsc#1221223)
This script makes sure fixed yum is installed.
(bsc#1221223)
- [x ] **Bug Fix** (a non-breaking change which fixes an issue)
- [ x] I have provided comments for any hard-to-understand code.
- [ x] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.
My changes are trivial, so I think changelog entry is not necessary, but nyway I wrote changelog entry.
Please use this space …
> make sure fixed version of yum (not affected with bsc#1221223) is installed

- app/controllers/api/connect/v3/systems/systems_controller.rb
- app/models/system.rb
- app/models/system_uptime.rb
- db/migrate/20240111200053_create_system_uptimes.rb
- db/schema.rb
- lib/suse/connect/system_serializer.rb
- lib/tasks/system_uptimes.rake
- package/files/systemd/rmt-uptime-cleanup.service
- package/files/systemd/rmt-uptime-cleanup.timer
- package/obs/rmt-server.changes
- package/obs/rmt-server.spec
- spec/factories/system_uptimes.rb
- spec/factories/systems.rb
- spec/lib/suse/connect/system_serializer_spec.rb
- spec/models/system_uptime_spec.rb
- spec/requests/api/connect/v3/systems/systems_controller_spec.rb
Uptime data is included in the data sent to SCC via RMT
https://jira.suse.com/browse/CSE-504
How to test this PR
On the client system clone https://github.com/SUSE/connect-ng/pull/202 ( this PR has the connect-ng changes for uptime tracking feature )
Also clone https://github.com/SUSE/uptime-tracker
On the RMT system, clone this code
Execute rails db:migrate to create the system_uptimes table
Start the server bin/rails server -b 0.0.0.0
Register the system on client system using command suseconnect --url <rmt_system_ip> , it should populate the …
> Adding Uptime tracking capability

- engines/instance_verification/lib/instance_verification/engine.rb
- engines/registry/spec/requests/api/connect/v3/systems/activations_controller_spec.rb
- engines/scc_proxy/lib/scc_proxy/engine.rb
- engines/zypper_auth/lib/zypper_auth/engine.rb
Remove `is_byos` param when updating the InstanceVerification cache, currently not used
> Remove BYOS param for updating the cache

- config/application.rb
> Use new cert for registry

- config/application.rb
- config/environments/test.rb
- engines/registry/config/environments/production.rb
- engines/registry/config/environments/test.rb
Move registry cache declaration for testing into the right engine
Move Registry engine config from core to its engine
Move registry cache directory declaration to the right engine
> Move registry engine config from core config to its engine

- config/environments/production.rb
The path agreed to use for the new cache is owned by root,
so new path set for registry and repository cache
> Set the cache path for repository and registry in a path owned by _rmt

- engines/registry/app/controllers/registry/registry_controller.rb
- engines/registry/app/models/access_scope.rb
- engines/registry/app/services/registry_catalog_service.rb
- engines/registry/spec/app/controllers/registry_controller_spec.rb
- engines/registry/spec/app/services/registry_catalog_service_spec.rb
Use the framework value to determine the full URL
and set it in the method instead of carrying over
the different methods and classes
Tests updated
> Do not carry over the request host, the URL is the same

- package/files/nginx-pubcloud/nginx-https.conf
The reference to the path where the cert for the registry is located was incorrect.
- [x ] **Bug Fix** (a non-breaking change which fixes an issue)
- [ x] I have verified that my code follows RMT's coding standards with `rubocop`.
- [x ] I have reviewed my own code and believe that it's ready for an external review.
> Fix the location for the registry cert

- engines/registry/lib/registry/engine.rb
> Fix wrongly named variable for the registry cache path

- public/tools/rmt-client-setup-res
This change fixes the use case when customer is registering LTSS on a CentOS/RHEL system that was previously registered as Linberty 7.
* Related Issue / Ticket / Trello card: https://jira.suse.com/browse/SLL-364
Automated tests (passed 4/4):
http://deliverance.suse.cz:8080/view/sll-test/job/sll-test-centos/89/
http://deliverance.suse.cz:8080/view/sll-test/job/sll-test-ol/28/
http://deliverance.suse.cz:8080/view/sll-test/job/sll-test-rhel/30/
http://deliverance.suse.cz:8080/view/sll-test/job/sll-test-sll/30/
- [-] I have documented the `MANUAL.md` file with any changes to the user experience.
Please check out our [review guidelines](https://github.com/SUSE/scc-docs/blob/master/team/workflow/code_revi …
> Fix rmt-client-setup-res use case when registering LTSS on an SLL7 system previously converted from CentOS/RHEL

- bin/rmt-cli
How to test: 
* Remove your rmt config file
* Run bin/rmt-cli sync
* See proper error message
> Print proper error message instead of stacktrace when rmt config cannot get read

- app/models/system.rb
- db/migrate/20240729103525_update_proxy_byos_column_type.rb
- db/schema.rb
Before LTSS support proxy_byos was a boolean column, representing PAYG or BYOS
With LTSS, we need a column (proxy_byos_mode) to represent one more value, change the type to enum with the following mapping:
PAYG -> 0
BYOS -> 1
LTSS -> 2
Create a system with `:hybrid`, should not produce an error
Check that the just created system has `hybrid` to true
> Add proxy_byos_mode column

- engines/registry/app/models/access_scope.rb
- engines/registry/spec/app/models/access_scope_spec.rb
- engines/registry/spec/data/access_policy_yaml.yml
- engines/scc_proxy/lib/scc_proxy/engine.rb
- engines/zypper_auth/lib/zypper_auth/engine.rb
- engines/zypper_auth/spec/requests/strict_authentication/authentication_controller_spec.rb
If the system is hybrid, it means is PAYG with an add on product (extension) activated. 
If instance metadata verification succeeded for that system, we check that the registration code is still valid.
* https://trello.com/c/D09lCvMp
* https://confluence.suse.com/display/publiccloud/LTSS+support+for+PAYG+instances
Running `zypper ref` or a `zypper` command on a hybrid system (PAYG with an add-on product activated) 
with a expired subscription should show access denied message
> Check access for repositories or registry for LTSS

- engines/instance_verification/lib/instance_verification/engine.rb
- engines/instance_verification/spec/requests/api/connect/v3/systems/products_controller_spec.rb
- engines/scc_proxy/lib/scc_proxy/engine.rb
- engines/scc_proxy/spec/requests/api/connect/v3/systems/products_controller_spec.rb
When registering a PAYG system with a registration code for an add-on product, if the product needs to be activated via SCC, do not raise the exception unless there is not token for the activation
Register a system with the LTSS regcode (new LTSS code on the client), this exception should not raise
> Handle non free extension with regcode

- engines/registry/app/controllers/registry/registry_controller.rb
- engines/registry/app/models/registry/authenticated_client.rb
- engines/registry/spec/app/controllers/registry_controller_spec.rb
- engines/registry/spec/app/models/registry/authenticated_client_spec.rb
- package/obs/rmt-server.changes
When container runtime tools on the client do not send the proper credentials or an exception happens during the catalog search, handle the exception
Put wrong credentials on `/etc/containers/config.json` 
and run `podman search foo` and autentication required message is shown
```bash
ec2-user@ip-172-31-21-235:~> sudo /usr/bin/cloudguestregistryauth 
Credentials refreshed
ec2-user@ip-172-31-21-235:~> podman search foo
ERRO[0000] error getting search results from v2 endpoint "registry-ec2.susecloud.net": authentication required 
Error: 1 error occurred:
* couldn't search registry "registry-ec2.susecloud.net": authentication required
ec2-user@ip-172-31-21-235:~> 
```
Please check out our [review …
> Handle the empty credentials from the container runtime tools on the client

- lib/rmt/gpg.rb
- package/obs/rmt-server.changes
- spec/lib/rmt/gpg_spec.rb
Harden our shellout commands to work with paths that contain special characters. This fixes a regression that came up with 2.18, after moving the temp. download location into the repository directory. We have some repositories that contain '$' in their path (eg.: '/repo/$RCE/RES7-SUSE-Manager-Tools/x86_64/')
Those get correctly escaped now.
How to reproduce: 
```
bin/rmt-cli products enable res-manager-client/7/x86_64
bin/rmt-cli mirror product res-manager-client/7/x86_64
```
> Harden our shellout commands to work with paths that contain special characters

- engines/scc_proxy/lib/scc_proxy/engine.rb
- engines/scc_proxy/spec/requests/api/connect/v4/systems/products_controller_spec.rb
When deactivating a product on a hybrid system, if there are no more non free product active for that system on SCC, that system is no longer hybrid but payg and should get updated on the db
- start a SLES 15.4 PAYG instance
- activate LTSS (`registercloudguest -r FOO`)
- check is active `SUSEConnect -l` and see LTSS being active
- remove LTSS (`SUSEConnect -d -p LTSS`)
- the system must be `payg` / 1 in the db, in the RMT server, access the db, and run
```SQL 
select proxy_byos_mode from systems where login = 'SCC_that_system_login'
```
The value for that field should be 1
and get …
> Update system from hybrid to payg if no more non free products active

- engines/registry/app/models/access_scope.rb
- engines/registry/spec/app/models/access_scope_spec.rb
When that header is missing, `podman search foo` would raise unauth exception
if the search uses a valid product like `podman search ltss` should return some paths but it returns nothing
Fails silently
> Use the right header for SCC activations

- engines/instance_verification/spec/requests/api/connect/v3/systems/products_controller_spec.rb
- engines/scc_proxy/lib/scc_proxy/engine.rb
Proxy the zypper migration upgrade call to SCC when the system is BYOS
- 15 SP3 BYOS instance
- register to RMT 2.19
- add LTSS
- update
- remove LTSS
- migrate to 15 SP4
- registercloudguest -r $LTSS_REGCODE
should work
> Propagate the upgrate call to SCC

- engines/scc_proxy/lib/scc_proxy/engine.rb
Set old proxy BYOS value until we drop that column
Register a BYOS system, it should have `proxy_byos` to `true` in the db
> Set old proxy BYOS value until we drop that column

- app/serializers/v3/product_serializer.rb
- engines/instance_verification/spec/requests/api/connect/v3/systems/products_controller_spec.rb
Before LTSS, the product serializer returned true for the free field of any product
That is no longer true in the Public Cloud scenario, where LTSS is not free
This Fixes that case
on a PAYG SLES 15.4 (or 15.3) activate LTSS, then on the client fetch all the extensions, LTSS should show up as not free
i.e.
```bash
ip-10-3-0-101:/home/ec2-user # fetch_extensions
[{'name': 'Basesystem Module', 'free': True}, {'name': 'SUSE Linux Enterprise Server LTSS', 'free': False}]
```
> Update the product serializer

- engines/registry/app/models/access_scope.rb
- engines/registry/spec/app/models/access_scope_spec.rb
When checking the registry access if system is hybrid, the check with SCC for the state of its activations should be done only with non free extensions, as base product is not free
This Fixes that scenario
on a PYG 15.4 system, register LTSS and run podman search
the result should include base product + LTSS
```bash
ip-10-3-0-101:/home/ec2-user # podman search registry-ec2.susecloud.net/
NAME                                                               DESCRIPTION
registry-ec2.susecloud.net/suse/hpc/warewulf4-x86_64/sle-hpc-node  
registry-ec2.susecloud.net/suse/ltss/sle15.4/bci-base              
registry-ec2.susecloud.net/suse/ltss/sle15.4/bci-base-fips         
registry-ec2.susecloud.net/suse/ltss/sle15.4/sle15                 
ip-10-3-0-101:/home/ec2-user # 
```
*Please select the …
> Check only extensions for SCC activations

- engines/scc_proxy/lib/scc_proxy/engine.rb
- engines/scc_proxy/spec/requests/api/connect/v3/systems/products_controller_spec.rb
When calling SccProxy scc_activate_product method, the response should be handled in that method as well
This helps reducing duplication and better responsibility separation
Also, new method to announce hybrid system to SCC
Update tests to reflect the changes
Activate a product from RMT to SCC , it should work as before
> Make SccProxy method responsible for handling the SCC request response

- engines/instance_verification/lib/instance_verification/providers/example.rb
- engines/instance_verification/spec/requests/api/connect/v3/systems/products_controller_spec.rb
- engines/scc_proxy/lib/scc_proxy/engine.rb
- engines/scc_proxy/spec/requests/api/connect/v3/systems/products_controller_spec.rb
- spec/factories/products.rb
- spec/factories/systems.rb
Azure basic images must not get access to LTSS product
Running an Azure basic image, trying to activate LTSS should fail
> Azure basic images do not get access to LTSS

- engines/instance_verification/lib/instance_verification/providers/example.rb
- engines/instance_verification/spec/requests/api/connect/v3/systems/products_controller_spec.rb
- engines/scc_proxy/lib/scc_proxy/engine.rb
When activating an extension, i.e. LTSS in Azure,
the header must contain the the instance identifier
This Fixes bsc#1233314
* Related Issue / Ticket / Trello card: https://bugzilla.suse.com/show_bug.cgi?id=1233314
on Azure, registering LTSS extension should work
> Send the instance ID in the token for Azure

- app/controllers/api/connect/base_controller.rb
- app/controllers/api/connect/v3/systems/products_controller.rb
- app/controllers/api/connect/v3/systems/systems_controller.rb
- app/controllers/api/connect/v4/systems/products_controller.rb
- app/controllers/application_controller.rb
- spec/requests/api/connect/base_controller_spec.rb
- spec/requests/api/connect/v3/systems/activations_controller_spec.rb
- spec/requests/api/connect/v3/systems/products_controller_spec.rb
- spec/requests/api/connect/v3/systems/systems_controller_spec.rb
- spec/requests/api/connect/v4/systems/products_controller_spec.rb
This PR targets to only rotate the token on calls to  PUT/POST/DELETE in system namespace
* Related Issue / Ticket / Trello card: https://trello.com/c/bimNtIHi/3647-repct-skip-system-token-rotation-in-read-only-apis
1. Show that calls to systems/ APIs don't rotate the token, only to [PUT/POST /systems/*](https://scc.suse.com/connect/v4/documentation#/systems/put_systems):
2. PUT /systems , PUT/POST/DELETE /systems/products
3. POST /systems/products/synchronize
4. Show that the current token gets returned in the response header
5. ~~Have it well documented in swagger~~ (RMT has no swagger)
```
> docker run --network=host --rm -ti registry.suse.com/suse/sle15:15.5 /bin/bash
$ zypper rm -y container-suseconnect
$ zypper in -y suseconnect-ng
$ suseconnect --url http://localhost:4224
$ cat …
```
> skip rotation for read Apis

- engines/instance_verification/app/controllers/instance_verification/billing_check_controller.rb
The verification code will check the headers of @request object in order to access the content of SUMA headers to grant access
Currently @request is nil coming from this code flow
This add the request to the call
Accessing @request object inside the provider verification code wihtin the instance-flavor-check code path should not crash
> Add request to billing check

- app/models/repository.rb
- lib/rmt/scc.rb
- spec/lib/rmt/scc_spec.rb
- Refined `make_local_path` to handle URLs from both SUSE domains (`https://updates.suse.com%` and `https://dl.suse.com%`) 
- The method is called during repository creation and update in rmt.
- Some repository URLs contain `/repo` in the path, such as `https://updates.suse.com/repo/$RCE/SLES10-SP4-LTSS-Updates/sles-10-x86_64/` in SCC. When synced and mirrored, these URLs would lead to incorrect directory paths locally.
- For example, the URL `https://updates.suse.com/repo/$RCE/...` would be updated to `https://dl.suse.com/repo/$RCE/...`. Without this fix, mirrored repositories would incorrectly create local paths like `/repo/repo/...`.
- The local path generation now correctly removes the `/repo` prefix, ensuring the correct local path structure.
- Updated …
> Refactor SUSE repo cleanup and local path generation logic supporting Akamai CDN

- lib/rmt/mirror/base.rb
- lib/rmt/mirror/repomd.rb
- package/obs/rmt-server.changes
- spec/lib/rmt/mirror/base_spec.rb
- spec/lib/rmt/mirror/repomd_spec.rb
This task is for cleaning up old metadata files after repository updates in the CDN.
https://trello.com/c/SznwZfr3/3662-l3-regression-rmt-doesnt-clean-up-metadata
```
1) Enable a repository using the command:  ` rmt-cli repos enable <repo-id>`
2) Run the mirror command:  ` rmt-cli mirror`
3) Rename any metadata file in the repodata directory (e.g., rmt/public/repo/SUSE/Products/SLE-Product-SLES/15-SP6/ppc64le/product/repodata).
4) Run the mirror command again: `   rmt-cli mirror`
Check whether it will remove the renamed metadata file from the repodata directory and download the updated one from the CDN.
```
- [* ] **Bug Fix** (a non-breaking change which fixes an issue)
> Rmt cleanup old metadata

- config/rmt.yml
- lib/rmt.rb
- lib/rmt/mirror/suma_product_tree.rb
- package/obs/rmt-server.changes
- package/obs/rmt-server.spec
- spec/lib/rmt/mirror/suma_product_tree_spec.rb
Allow user to configure the SUMA product tree base URL in RMT's config file `mirroring.suma_product_tree_base_url` attribute. The configured value takes precedence over the default (https://scc.suse.com/suma/).
* Related Issue / Ticket / Trello card: https://trello.com/c/Fv5zbDoj/3694-rgs-configure-suma-product-tree-base-url-in-rmt
On your local setup, change the attribute `mirroring.suma_product_tree_base_url` on `config/rmt.local.yml` to point to a custom URL (the URL must be reachable and respond to `<custom URL>/product_tree.json`, e.g.:
```yaml
mirroring:
mirror_src: false
verify_rpm_checksums: false
dedup_method: hardlink
suma_product_tree_base_url: <custom URL>/suma/
```
Then, run `bin/rmt-cli mirror`, and verify that the log output shows that the mirroring process has finished …
> Configure SUMA product tree base URL

- lib/rmt.rb
- lib/rmt/mirror/suma_product_tree.rb
- package/obs/rmt-server.changes
- package/obs/rmt-server.spec
- package/obs/rmt.conf
- spec/lib/rmt/mirror/suma_product_tree_spec.rb
Fix bug that hardcoded the SUMA product tree URL to 'scc.suse.com' even if a different host was specified in the RMT configuration file.
* Related Issue / Ticket / Trello card: https://bugzilla.suse.com/show_bug.cgi?id=1234844
1. Edit `config/rmt.local.yml` and change `scc.host` to point to a different host than `https://scc.suse.com/connect`, e.g.: `http://localhost:3000/connect`
1. On the project root directory, run `bin/rmt-cli mirror --debug`. If the command succeeds in downloading the SUMA product tree, it should print a similar output:
```log
I, [2025-01-03T12:19:11.738742 #1623]  INFO -- : Mirroring SUSE Manager product tree to <...>/rmt/public/suma/
D, [2025-01-03T12:19:11.741255 #1623] DEBUG -- : HTTP request for: http://localhost:3000/suma/product_tree.json
I, …
```
> Fix hardcoded suma tree url

- engines/instance_verification/spec/requests/api/connect/v3/systems/products_controller_spec.rb
- engines/registry/spec/requests/api/connect/v3/systems/activations_controller_spec.rb
- engines/scc_proxy/lib/scc_proxy/engine.rb
- engines/strict_authentication/app/controllers/strict_authentication/authentication_controller.rb
- engines/strict_authentication/spec/requests/strict_authentication/authentication_controller_spec.rb
- engines/zypper_auth/lib/zypper_auth/engine.rb
- engines/zypper_auth/spec/requests/strict_authentication/authentication_controller_spec.rb
- package/obs/rmt-server.changes
- spec/factories/systems.rb
When a hybrid system runs zypper command, the check
needs to take care of the subscription verification
Currently, the check lacks paid extension ID, resulting in
an unsuccessful verification
This change fixes that
If system is hybrid, and the path being accessed belongs to a paid extension,
we check that the paid extension subscription is active
if the repository path belongs to a free repository or no matches with paid extensions,
no need to check the subscription
if ZypperAuth handle_scc_subscription method gets called without a product id,
the method will check _all_ non free products suscriptions to be active, if any
This fixes bsc#1230157
* Related Issue / Ticket / Trello card: https://bugzilla.suse.com/show_bug.cgi?id=1230157
Start an Azure instance, register LTSS, wait > 20 min …
> Update Zypper auth check

- engines/instance_verification/config/environments/production.rb
- engines/registration_sharing/package/rmt-server-trim-cache.service
- package/obs/rmt-server.changes
Add the new cache directories and their expiration times to the cache scrubber 
This is a step in the list of steps to reduce queries to SCC
with this changes in place, restarting RMT should show the new cache directories in /var/lib/rmt/rmt-cache-trim.sh
> Update cache scrubber

- engines/registration_sharing/app/controllers/registration_sharing/rmt_to_rmt_controller.rb
- engines/registration_sharing/spec/requests/registration_sharing/rmt_to_rmt_controller_spec.rb
When creating or updating a system during regsharing, use the full unique combination
This Fixes bsc#1236600
* Related Issue / Ticket / Trello card: https://bugzilla.suse.com/show_bug.cgi?id=1236600
> filter by the whole key

- config/initializers/routing_error_logger.rb
- engines/strict_authentication/spec/requests/strict_authentication/authentication_controller_spec.rb
This Fixes #1300
* Related Issue / Ticket / Trello card: #1300 
Try a non existing route and the RMT log should not have FATAL for that query
> Do not log FATAL when routing error

- engines/instance_verification/lib/instance_verification/engine.rb
- engines/registry/lib/registry/engine.rb
- engines/registry/spec/requests/api/connect/v3/systems/activations_controller_spec.rb
- engines/zypper_auth/lib/zypper_auth/engine.rb
As agreed, the verify_instance method should be in the InstanceVerification class
Update tests
Zypper operations should keep the same behaviour 
> Move verify_instance from ZypperAuth to InstanceVerification class

- app/controllers/api/connect/v3/systems/products_controller.rb
- lib/rmt/cli/export.rb
- lib/rmt/cli/import.rb
- locale/rmt.pot
- spec/requests/api/connect/v3/systems/products_controller_spec.rb
- spec/support/shared_examples/product_checks.rb
Update POT file with proof read strings and the source code
* Related Issue / Ticket / Trello card: https://trello.com/c/yvuDdbhJ/3833-translation-round-ask-for-proofread
> Update source code with proofread strings

- engines/scc_proxy/lib/scc_proxy/engine.rb
- engines/scc_proxy/spec/requests/api/connect/v3/systems/products_controller_spec.rb
When a PAYG system activates a product like LTSS, the system gets announce to SCC
That request can fail and the error needs to be handled
This Fixes #1316
* Related Issue / Ticket / Trello card:  #1316
An error on that scenario should log the error and not produce a FATAL error
> Error handling for hybrid system being announced to SCC

- engines/instance_verification/config/environments/development.rb
- engines/instance_verification/lib/instance_verification/engine.rb
- engines/instance_verification/spec/requests/api/connect/v3/systems/products_controller_spec.rb
- engines/registry/lib/registry/engine.rb
- engines/registry/spec/requests/api/connect/v3/systems/activations_controller_spec.rb
- engines/scc_proxy/lib/scc_proxy/engine.rb
- engines/scc_proxy/spec/requests/api/connect/v3/systems/products_controller_spec.rb
- engines/strict_authentication/app/controllers/strict_authentication/authentication_controller.rb
- engines/strict_authentication/spec/requests/strict_authentication/authentication_controller_spec.rb
- engines/zypper_auth/spec/requests/api/connect/v3/systems/activations_controller_spec.rb
- engines/zypper_auth/spec/requests/services_controller_spec.rb
- engines/zypper_auth/spec/requests/strict_authentication/authentication_controller_spec.rb
- spec/factories/systems.rb
We need to update the cache key to add a unique identifier
for systems running Zypper operations if we want to find them in the cache
As some workflows check a part/half the cache key not the whole cache key
The unique identifer is the instance id, unique and present across all CSPs
When registering a system or running a zypper operation, the cache entry must include the instance id of that system
> Update cache key

- engines/instance_verification/lib/instance_verification/engine.rb
- engines/instance_verification/spec/requests/api/connect/v3/systems/products_controller_spec.rb
- engines/registry/app/controllers/registry/registry_controller.rb
- engines/registry/app/models/access_scope.rb
- engines/registry/spec/app/models/access_scope_spec.rb
- engines/registry/spec/requests/api/connect/v3/systems/activations_controller_spec.rb
- engines/scc_proxy/lib/scc_proxy/engine.rb
- engines/scc_proxy/spec/requests/api/connect/v3/systems/products_controller_spec.rb
- engines/strict_authentication/app/controllers/strict_authentication/authentication_controller.rb
- engines/zypper_auth/spec/requests/strict_authentication/authentication_controller_spec.rb
- spec/factories/systems.rb
Update the SCC subscription check method to first look for the subscription
in the cache
Update the call of the method
Update build cache as scc subscription check from registry uses product class
running zypper or registry catalog should use the cache
> Add subscription check cache

- engines/data_export/lib/data_export/engine.rb
- engines/data_export/spec/requests/api/connect/v3/systems/products_controller_spec.rb
- engines/data_export/spec/requests/api/connect/v3/systems/systems_controller_spec.rb
Send the information to data warehouse whenever a system activates or upgrades a product
* Related Issue / Ticket / Trello card: https://trello.com/c/n8vD9v1b
With the DataExport engine on, the activation of a product should trigger the data export method
> Export data when system activates or upgrades a product

- .gitignore
- Dockerfile
- Gemfile.lock
- Makefile
- ci/rmt-build-rpm
- ci/rmt-run-feature-tests
- docker-compose.yml
- package/obs/rmt-server.spec
Bundler had a major upgrade on SP6 due to CVEs which renders the 1.x branch unusable. This needs to be taken into account in the CI and additionally also in the spec file.
Here try to fix to get CI working again and make building RMT a little bit more easy.
The PR does:
- Fix the CI running the new version
- Move `make dist` into a container rather running on the development maschine
- Replace bundler version on rpm build time with the available from the build environment
NOTE: The updated bundler (2.2.34) version is now available on almost all service packs
card: https://trello.com/c/FpA0HZsY/3900-fix-rmt-package-building-on-obs
**How to test this merge request:**
- RMT CI is working again
- make dist:
```
$ make dist
```
- build against SLESSP7 (which not yet has the 2.2.34 update)
``` …
```
> Bump bundler to 2.2.34 to build on SP6

- engines/instance_verification/lib/instance_verification/engine.rb
- engines/scc_proxy/lib/scc_proxy/engine.rb
Missing decoding of instance data for BYOS path
register a BYOS i.e. `ami-0ebae39929f571942` (for eu-central-1) `suse-sles-15-sp6-byos-v20250409-hvm-ssd-x86_64` should succeed
> Use decoded instance data to create the cache

- engines/instance_verification/lib/instance_verification/engine.rb
- engines/registry/app/models/access_scope.rb
- engines/registry/spec/app/models/access_scope_spec.rb
- engines/scc_proxy/lib/scc_proxy/engine.rb
- engines/strict_authentication/app/controllers/strict_authentication/authentication_controller.rb
- engines/zypper_auth/spec/requests/strict_authentication/authentication_controller_spec.rb
For some paths of BYOS, scc_check_subscription needs the cache parameters
This change adds said parameters
Update the method calls and tests
Register a BYOS i.e. ami-0ebae39929f571942 (for eu-central-1) suse-sles-15-sp6-byos-v20250409-hvm-ssd-x86_64 should succeed
> Add cache parameters to create the cache for BYOS or HYBRID

- app/models/repository.rb
- spec/lib/rmt/scc_spec.rb
We want to assert RMT works with RGS' CDN domain name. Here in RMT we are removing the RGS (rancher) repos without auth tokens.
* Related Issue / Ticket / Trello card: https://trello.com/c/dm1h7IUR/3882-rgs-s-assert-rmt-works-with-rgs-cdn-domain-name
N/A
> Remove RGS repos without auth tokens

- app/models/system.rb
- spec/models/system_spec.rb
There is no need to run validations for activations or to instantiate all the activations objects from the DB when destroying a system
Changing `:destroy` to `:delete_all` reduce the DB queries considerably, while keeping consistency with regsharing (unaffected)
current queries for deleting a system
```bash
INFO: System with login \"SCC_b678091eb6e2496b9dae93376e44b18a\" authenticated, system  token \"i-030b5a7f188ea1821\"
DEBUG:   TRANSACTION (0.1ms)  BEGIN
DEBUG:   Activation Destroy (0.3ms)  DELETE FROM `activations` WHERE `activations`.`id` = 9577795
DEBUG:   System Exists? (0.2ms) SELECT 1 AS one FROM `systems` WHERE `systems`.`system_token` = 'i-030b5a7f188ea1821' AND `systems`.`id` != 891691 AND `systems`.`login` = 'SCC_b678091eb6e2496b9dae93376e44b18a' AND `systems`.`password` = …
```
> Change the way activations are deleted when a system is deleted

- engines/instance_verification/app/controllers/instance_verification/billing_check_controller.rb
- engines/instance_verification/lib/instance_verification/engine.rb
- engines/instance_verification/lib/instance_verification/providers/example.rb
- engines/instance_verification/spec/requests/api/connect/v3/systems/products_controller_spec.rb
- engines/instance_verification/spec/requests/instance_verification/billing_check_controller_spec.rb
- engines/scc_suma_api/app/controllers/scc_suma_api/scc_suma_api_controller.rb
- engines/scc_suma_api/spec/requests/scc_suma_api/scc_suma_api_controller_spec.rb
RMT should not produce 500 errors, any time we parse or validate
the instance metadata we should handle the possible exceptions
Try to register an instance, activate a product with wrong metadata should not produce 500 error
Running instance billing flavor check from the client with wrong metadata that 
- could not be parsed: should not produce 500 error
- could be parsed but not verified: should not produce 500 error
> Catch parsing exceptions

- app/models/system.rb
- engines/instance_verification/lib/instance_verification/engine.rb
- engines/instance_verification/spec/requests/api/connect/v3/systems/products_controller_spec.rb
- engines/registry/spec/requests/api/connect/v3/systems/activations_controller_spec.rb
- engines/scc_proxy/spec/requests/api/connect/v3/systems/products_controller_spec.rb
- engines/strict_authentication/spec/requests/services_controller_spec.rb
- engines/strict_authentication/spec/requests/strict_authentication/authentication_controller_spec.rb
- engines/zypper_auth/spec/requests/api/connect/v3/systems/activations_controller_spec.rb
- engines/zypper_auth/spec/requests/strict_authentication/authentication_controller_spec.rb
- spec/factories/systems.rb
- spec/models/system_spec.rb
Refresh or update the instance data in the DB, before RMT 2.22 there was no need to do this
as the instance data was fresh from the client, after 2.22 we are using instance data from the DB 
and we need to refresh that data
Run a zypper up on a already registered instance with instance data on the DB and that instance data should get updated on the DB
> Update instance data

- app/models/system.rb
- engines/instance_verification/lib/instance_verification/providers/example.rb
- engines/instance_verification/spec/requests/api/connect/v3/subscriptions/systems_controller_spec.rb
- engines/registry/spec/requests/api/connect/v3/systems/activations_controller_spec.rb
- engines/scc_proxy/lib/scc_proxy/engine.rb
- engines/scc_proxy/spec/requests/api/connect/v3/subscriptions/systems_controller_spec.rb
- engines/scc_proxy/spec/requests/api/connect/v3/systems/products_controller_spec.rb
- engines/scc_proxy/spec/requests/api/connect/v4/systems/products_controller_spec.rb
Instance id is guarantee to be unique across the three CSPs, thus we do not need to generate a pseudo unique login value
This would help also with duplicated systems detection
On a public cloud environment, with this changed applied the system should have the instance id as a login:
> Use instance id as a login on the public cloud environment

- engines/instance_verification/lib/instance_verification/engine.rb
- engines/instance_verification/spec/requests/api/connect/v3/systems/products_controller_spec.rb
- engines/scc_proxy/lib/scc_proxy/engine.rb
- engines/scc_proxy/spec/requests/api/connect/v3/subscriptions/systems_controller_spec.rb
- engines/scc_proxy/spec/requests/api/connect/v3/systems/products_controller_spec.rb
- engines/strict_authentication/spec/requests/services_controller_spec.rb
whenever we call instance verification plugin methods, an exception can raise
Handle the possible exception to not return 500 error
Make the methods for Instance Verification plugin to raise an exception
i.e., use wrong metadata or blank metadata, the request should return 422 not 500
and an appropiate error message, for example on GCP, with a borked token.
```bash
jesus-verify-exp:/home/jesusbv # registercloudguest
Registering system to registration proxy https://smt-gce.susecloud.net
Announcing system to https://smt-gce.susecloud.net ...
Error: Registration server returned 'Token decoding error: Could not find public key for kid 8e8fc8e556f7a76d08d35829d6f90ae2e12cfd0d' (422)
jesus-verify-exp:/home/jesusbv # 
```
*Please select …
> Handle instance verification exceptions

- Makefile
Once public/repo has been populated by a running RMT it may not be possible to update the permissions on files due to ownership changes. Also quieten the associated error messages.
> Ignore errors when setting public permissions

- DEVELOPMENT.md
- Makefile
- db/schema.rb
- docker-compose.yml
As it appears that only the public/repo directory requires modified permissions, enhance the Makefile build rules to ensure that those permissions are being applied to the directory after ensuring that it exists, and avoid changing the permissions for other files and directories under public.
Update the docker-compose.yml's MariaDB version to match the version found in SLE 15 SP7, namely version 10.11, and switch to using the SUSE built version, available from registry.suse.com.
Updated db/schema.rb:
* Updated charset and collation settings triggered by running the rails db:migrate against the SLE 15 SP7 MariaDB 10.11 DB.
* Re-orders the proxy_byos_mode and system_information fields in the systems table, adding a collation setting for the latter.
* Adds the missing pubcloud_reg_code field …
> docker compose development environment enhancements

- engines/data_export/lib/data_export.rb
- engines/data_export/lib/data_export/engine.rb
- package/obs/rmt-server.spec
if there are more than one handler for the data exporter, RMT will fail
Under the scenario of someone implementing their own handler, i.e. foo.rb and placing it there, they may rename or move example.rb and that would be OK
but if RMT gets updated it will place example.rb in the same location, making two handlers for the data exporter when it should be only one
This fixes that scenario and fixes bsc#1248869
* Related Issue / Ticket / Trello card: [bsc#1248869](https://bugzilla.suse.com/show_bug.cgi?id=1248869
)
On a server with RMT and data export engine with a handler, i.e. handler.rb, example.rb should be move to example in the same directory
Please check out our [review …
> Fix only one handler for data exporter
