.travis.yml

Make Travis check the master and branches

---

README.md

Add travis master status

---

lib/rmt/downloader.rb

Bug fix for writing HTTP body chunks on download.

Fix file write 4458

---

.gitignore

Do not track dot secrets fie :potato:

---

app/models/product.rb
bin/rmt-products
lib/database.rb
lib/rmt/products.rb
spec/models/product_spec.rb

Since I accidentally deleted the source branch, let's give this another try!
See also https://github.com/SUSE/rmt/pull/22

Rmt products command

---

Gemfile
Gemfile.lock

see https://github.com/puma/puma/issues/1380

Fixes installation on darwin

---

README.md

In the setup section the readme still mentioned postgresql instead of mysql. I replaced it accordingly :)

Replaced postgresql with mysql in the setup section.

---

.rspec
Gemfile
Gemfile.lock

:cool: https://github.com/thekompanee/fuubar
I like it. Any objections? @ikapelyukhin

Use Fuubar formatter

---

lib/rmt/cli/repos.rb
spec/lib/rmt/cli/repos_spec.rb

Print message about syncing on empty database

---

lib/rmt/cli/export.rb
lib/rmt/scc.rb
lib/suse/connect/api.rb
spec/lib/rmt/scc_spec.rb
spec/suse/connect/api_spec.rb

Export products unscoped too 4719

---

.gitignore
Makefile
README.md
package/rmt-server.spec

Please review the following changes:
* 6dde7c6 improve worksflow to initialize package dir
* 702de6c ignore _link file
* 82f478e fix file permissions of yard gem

[Review] Request from 'digitaltom' @ 'SUSE/rmt/review_171228_packaging_fixes'

---

package/rmt-server.changes
package/rmt-server.spec

Please review the following changes:
* 733894c changelog
* bb04d95 do not build on s390 (bsc#1082150)

[Review] Request from 'digitaltom' @ 'SUSE/rmt/review_180222_do_not_build_on_s390'

---

package/rmt-server.conf

Point nginx to /usr/share/rmt/public

---

.github/ISSUE_TEMPLATE.md
README.md
lib/rmt/cli/base.rb

* Add a issue template for the issue tracker
* Add a feedback section to the README.md
* Add information about feedback to the help output

Promote feedback

---

app/controllers/api/connect/base_controller.rb
lib/action_controller/parameter_missing_translated.rb

Replace ParameterMissingTranslated with TranslatedError

---

README.md

They are needed to run `make dist`

Add nokogiri dependencies to README

---

app/controllers/api/connect/v3/systems/products_controller.rb
app/controllers/api/connect/v4/repositories/installer_controller.rb
app/controllers/api/connect/v4/systems/products_controller.rb
spec/requests/api/connect/v3/systems/products_controller_spec.rb
spec/requests/api/connect/v4/repositories/installer_controller_spec.rb
spec/requests/api/connect/v4/systems/products_controller_spec.rb

* Better handle incorrect product versions coming into rmt (use of "-")

Fixed broken rollback

---

app/controllers/api/connect/v3/systems/products_controller.rb
spec/requests/api/connect/v3/systems/products_controller_spec.rb

* don't check activations on upgrade
* delete old activations that are successors/predecessors
* activate new product

Fix upgrade endpoint

---

.gitignore
MANUAL.md
Makefile
README.md
package/rmt-server.spec

~~:construction: The formatting is still pretty broken :construction:~~

Split off usage instruction into manual.md

---

.travis.yml
config/boot.rb
config/rmt.yml
lib/rmt/config.rb
lib/rmt/http_request.rb
lib/rmt/mirror.rb
lib/rmt/scc.rb
package/rmt.conf

1. Added default values for database section;
2. Now uses safe navigation when accessing nested parameters.

Safer configuration

---

README.md

Also, link to the product page.

Fix wording on Expanded Support

---

lib/rmt/cli/products.rb
lib/rmt/cli/repos.rb
lib/rmt/cli/repos_custom.rb
package/rmt-server.changes

- products
- repos
- custom reps

order list items for output

---

MANUAL.md
README.md
lib/rmt/cli/base.rb
lib/rmt/config.rb
package/rmt-server.spec
spec/lib/rmt/cli/main_spec.rb

After discussion: Moving `/etc/rmt/rmt.conf` back to `/etc/rmt.conf`

The definite location

---

lib/rmt/cli/base.rb
lib/rmt/cli/decorators.rb
lib/rmt/cli/decorators/base.rb
lib/rmt/cli/decorators/custom_repository_decorator.rb
lib/rmt/cli/decorators/custom_repository_products_decorator.rb
lib/rmt/cli/decorators/product_decorator.rb
lib/rmt/cli/decorators/repository_decorator.rb
lib/rmt/cli/products.rb
lib/rmt/cli/repos.rb
lib/rmt/cli/repos_custom.rb
package/rmt-server.changes
spec/lib/rmt/cli/decorators/base_spec.rb
spec/lib/rmt/cli/products_spec.rb
spec/lib/rmt/cli/repos_custom_spec.rb
spec/lib/rmt/cli/repos_spec.rb

* Output of boolean fields in table to translated strings
* The cli classes became too big with out the output handling. Let's separate that logic to a class responsible for only that.

CLI Table/CSV Cleanup

---

lib/rmt.rb
lib/rmt/cli/smt_importer.rb
package/rmt-server.changes
package/rmt-server.spec
spec/lib/rmt/cli/smt_importer_spec.rb

Add trailing slashes to custom repository urls on import from smt.

---

lib/rmt/misc.rb
package/nginx-http.conf
spec/lib/rmt/misc_spec.rb

- Redirect /repo/repoindex.xml from HTTP to HTTPS
- Include auth subrequest into /repo location

Fix HTTP vhost config

---

app/controllers/api/connect/v3/systems/activations_controller.rb
spec/requests/api/connect/v3/systems/activations_controller_spec.rb

Fixes #148, fix explaination [in the comment](https://github.com/rails-api/active_model_serializers/issues/1954#issuecomment-255968665).

Fix nested serializers in system/activations

---

lib/rmt/logger.rb
package/rmt-server.changes
spec/lib/rmt/logger_spec.rb

Fixes #336. Got too tired of seeing all the debug stuff in my logs :-)

Supply log severity to journald

---

lib/rmt/cli/export.rb
lib/rmt/cli/products.rb
lib/rmt/cli/repos.rb
lib/rmt/mirror.rb

SUMA is the proper name of the product.

Change SUMA to SUSE Manager

---

spec/lib/rmt/mirror_spec.rb

Travis didn't pick up the test failure before so this failed test got into master without us realizing.

Fix suma product tree mirror spec

---

bin/rmt-test-regsharing
engines/registration_sharing/lib/registration_sharing/client.rb
engines/registration_sharing/lib/registration_sharing/engine.rb
engines/registration_sharing/spec/models/activation_spec.rb

* Make regsharing test script usable by monitoring
* Don't trigger regsharing on model updates (currently it's triggered when `system.last_seen_at` is updated)

Regsharing improvements

---

lib/rmt.rb
lib/rmt/downloader.rb
package/obs/rmt-server.changes
package/obs/rmt-server.spec
spec/lib/rmt/mirror_spec.rb

Preserve cache timestamps

---

integration/run.sh

Fixes CI failing on https://github.com/SUSE/rmt/pull/502 because DB is not cleaned up

Cleanup DB before Prophet run

---

package/obs/rmt-server.spec

Goes together with https://github.com/yast/yast-rmt/pull/53.

Recommend yast2-rmt v1.3.0 that can enable new timers

---

lib/rmt.rb
package/obs/rmt-server.changes
package/obs/rmt-server.spec
spec/lib/rmt/http_request_spec.rb

Test if low_speed_time and low_speed_limit can be changed

Check for a configurable low_speed_time and low_speed_limit

---

Gemfile
Gemfile.lock
db/migrate/20181030125058_add_migration_extra_to_products_extensions.rb
db/migrate/20200205123840_backfill_add_migration_extra_to_products_extensions.rb
db/schema.rb
lib/rmt.rb
package/obs/rmt-server.changes
package/obs/rmt-server.spec

Fix migrations in case adding migration_extra column failed

---

Gemfile
Gemfile.lock

Fix build issues on tumbleweed.

Increase mysql2 gem from 0.4.10 to 0.5.3

---

lib/rmt.rb
package/obs/rmt-server.changes
package/obs/rmt-server.spec

Add missing version bump for `rmt-cli products show` command

Bump version to 2.5.5

---

CONTRIBUTORS
LICENSE

Updated contributors and license copyright date.

Updated contributors

---

MANUAL.md
lib/rmt.rb
lib/rmt/cli/systems.rb
package/files/rmt-cli_bash-completion.sh
package/obs/rmt-server.changes
package/obs/rmt-server.spec
spec/lib/rmt/cli/systems_spec.rb

Changelog for pr #556

---

lib/rmt.rb
package/obs/rmt-server.changes
package/obs/rmt-server.spec

Bump to version 2.6.5
Notes:
* I also fixed wrong date names from previous changes.

Bump to version 2.6.5

---

PACKAGE.md

This is to help avoid missing MRs in the future again, as it's easy to
overwrite a previous MR.

Make a note about superseding MRs in package process

---

docs/smt_and_rmt.md

Update the SMT / RMT comparison chart, specifying the supported versions of RES.

Update SMT/RMT comparison table

---

.rubocop_todo.yml
MANUAL.md
app/models/product.rb
lib/rmt/cli/products.rb
package/files/rmt-cli_bash-completion.sh
spec/lib/rmt/cli/products_spec.rb

Enhance products listing adding filtering by
- name or identifier
- version
- architecture
Fixes #655 and #656

Add filter options for product listing

---

lib/rmt.rb
package/obs/rmt-server.changes
package/obs/rmt-server.spec

Bump to version 2.6.6

---

package/obs/rmt-server.changes
package/obs/rmt-server.spec

Fixed build: `osc build SLE_15_SP3`

Fix rpath commands in sle15 sp3 packaging

---

lib/rmt/cli/base.rb
lib/rmt/cli/products.rb
lib/rmt/cli/repos.rb
lib/rmt/cli/repos_base.rb
locale/rmt.pot
spec/lib/rmt/cli/main_spec.rb
spec/lib/rmt/cli/products_spec.rb
spec/lib/rmt/cli/repos_custom_spec.rb
spec/lib/rmt/cli/repos_spec.rb

card: https://trello.com/c/wZ4PnOY9/1859-translation-round-ask-for-translations
**How to test the changes**:
There are no real changes for now. What you can do is incorporate the changes into the po files and check the in `bin/rmt-cli`
Thanks for reviewing!

Added new pot files after proofreading

---

lib/rmt.rb
package/obs/rmt-server.changes
package/obs/rmt-server.spec

This PR removes a future release version 2.6.10 and merges the release
notes

Cleanup unreleased patch version

---

package/obs/rmt-server.spec

Update nio4r build flags

---

.travis.yml
Gemfile.lock

Update ruby 2.5 on travis runners

---

contrib/get_repository_tokens.rb

This PR adds a ruby port of `contrib/get_repository_token.py` script.

Get repository token script

---

package/obs/rmt-server.changes

Fix typo in rmt changes version string

Fix patch version string

---

lib/rmt.rb
package/obs/rmt-server.changes
package/obs/rmt-server.spec

Release notes for 2.6.10

---

config/rmt.yml
docker-compose-test.yml
docker-compose.yml
lib/rmt/cli/base.rb
lib/rmt/cli/mirror.rb
lib/rmt/downloader.rb
lib/rmt/gpg.rb
lib/rmt/scc.rb
package/obs/rmt-server.changes
package/obs/rmt.conf

* Additional debug output for 'mirror' command to see timestamps
* CLI debug output can get enabled from config file

Additional debug output for 'mirror' command

---

docs/smt_and_rmt.md

This PR updates the comparison document for RMT and SMT.

Update rmt & smt docs

---

.rubocop_todo.yml
engines/scc_proxy/lib/scc_proxy/engine.rb
engines/scc_proxy/spec/requests/api/connect/v3/systems/systems_controller_spec.rb
engines/scc_proxy/spec/requests/api/connect/v4/systems/products_controller_spec.rb
package/obs/rmt-server.changes

De-register BYOS proxy systems from SCC

Add system deregistration for BYOS proxy

---

.rubocop_todo.yml
engines/scc_proxy/lib/scc_proxy/engine.rb
engines/scc_proxy/spec/requests/api/connect/v3/systems/systems_controller_spec.rb
engines/scc_proxy/spec/requests/api/connect/v4/systems/products_controller_spec.rb
package/obs/rmt-server.changes

Re-adding product deactivation code that got unintentionally removed with https://github.com/SUSE/rmt/pull/786

Re-add pubcloud BYOS system/product de-activation

---

engines/scc_proxy/lib/scc_proxy/engine.rb
engines/scc_proxy/spec/requests/api/connect/v3/systems/systems_controller_spec.rb

Drop unneeded code that tried to de-activate all products before deleting the system.

---

package/obs/rmt-server.changes

Revise obs changelog

---

package/obs/rmt-server.changes
package/obs/rmt-server.spec

Fix ruby3 factory builds

---

package/obs/rmt-server.spec

Fixes https://bugzilla.suse.com/show_bug.cgi?id=1195759
- [x **Bug Fix** (a non-breaking change which fixes an issue)

Don't fail the %post script which reloads nginx config if nginx is not running

---

db/schema.rb
lib/rmt/cli/decorators/base.rb
lib/rmt/cli/decorators/system_decorator.rb
lib/rmt/cli/systems.rb

Change suggestion for the review of PR #842.

Suggestions for PR #842

---

lib/rmt/cli/systems.rb
spec/lib/rmt/cli/systems_spec.rb

As discussed, some of the messages needed a bit more of clarification.

cli: improved the messages on purging systems

---

.github/stale.yml

Added the stale bot, which will allow us to have more awareness on pull requests which are stuck in the development process.

github: added the stale bot

---

integration/install.sh

Integration tests: Install osc by default

---

integration/install.sh
integration/prophet/.prophet_ci.yml
integration/run.sh

Fix RMT jenkins integration tests

---

engines/registration_sharing/app/controllers/registration_sharing/rmt_to_rmt_controller.rb
engines/registration_sharing/lib/registration_sharing/client.rb
engines/registration_sharing/spec/lib/registration_sharing/client_spec.rb

Add `proxy_byos` attribute into the registration sharing

Add proxy_byos attribute into the registration sharing

---

lib/rmt.rb
package/obs/rmt-server.changes
package/obs/rmt-server.spec

prepare release of 2.9

---

db/schema.rb
lib/rmt/scc.rb
lib/suse/connect/api.rb
spec/lib/rmt/scc_spec.rb
spec/lib/suse/connect/api_spec.rb

Fix rmt failed sync handing

---

package/obs/rmt-server.changes
public/tools/rmt-client-setup-res

adapt rmt-client-setup-res script for new SuSE Liberty Linux 9 release. 
- [ x] **New Feature** (a non-breaking change which adds new functionality)
- [ x] I have provided comments for any hard-to-understand code.
- [ x] RMT's test coverage remains at 100%.

adapt rmt-client-setup-res script for new SuSE Liberty Linux 9 release

---

lib/rmt/deduplicator.rb
spec/lib/rmt/deduplicator_spec.rb

source file ← target # hardlink
source file → target # copy

Change the log output when hardlinking, to distinguish from copy:

---

lib/rmt/cli/systems.rb

Added a note on the value for inactive systems

---

engines/instance_verification/README.md

Update instance verification README

---

engines/registration_sharing/app/controllers/registration_sharing/rmt_to_rmt_controller.rb
engines/registration_sharing/lib/registration_sharing/client.rb
engines/registration_sharing/spec/lib/registration_sharing/client_spec.rb

Add `system_token` attribute into the registration sharing

Add system_token attribute into the registration sharing

---

engines/instance_verification/lib/instance_verification/engine.rb

Log instance verification exceptions

---

engines/strict_authentication/app/controllers/strict_authentication/authentication_controller.rb
engines/strict_authentication/spec/requests/strict_authentication/authentication_controller_spec.rb

- If product is any if of the SUMA products allow access to those channels
Allow access to SUMa channels

Add SUMA channels

---

engines/instance_verification/app/controllers/instance_verification/billing_check_controller.rb
engines/instance_verification/lib/instance_verification/providers/example.rb
engines/scc_proxy/lib/scc_proxy/engine.rb

Method update in order to cover all CSPs

Update method for all CSPs

---

lib/rmt.rb
package/obs/rmt-server.changes
package/obs/rmt-server.spec

New release

---

config/routes.rb
engines/scc_suma_api/app/controllers/scc_suma_api/scc_suma_api_controller.rb
engines/scc_suma_api/spec/requests/scc_suma_api/scc_suma_api_controller_spec.rb

The endpoints SUMa needs on RMT must be the same path as SCC

Scc endpoints

---

engines/scc_suma_api/app/controllers/scc_suma_api/scc_suma_api_controller.rb
engines/scc_suma_api/spec/requests/scc_suma_api/scc_suma_api_controller_spec.rb

SUMa prefers use of headers, similar behaviour as SCC endpoints

Use headers metadata

---

engines/scc_suma_api/app/controllers/scc_suma_api/scc_suma_api_controller.rb
engines/scc_suma_api/spec/requests/scc_suma_api/scc_suma_api_controller_spec.rb

- Add test for that check
Check for BYOS registered systems when auth for unscoped products SCC endpoint

Check for BYOS registered systems

---

lib/rmt.rb
package/obs/rmt-server.changes
package/obs/rmt-server.spec

Add a Changelog entry for 2.15 to prepare for the release.

Version 2.15

---

lib/rmt/cli/clean.rb

After an internal proofreading round, some strings needed to be updated to improve the text.

Update strings marked for translation

---

.rubocop_todo.yml
config/rmt.yml
lib/rmt/cli/base.rb
lib/rmt/cli/export.rb
lib/rmt/cli/import.rb
lib/rmt/cli/mirror.rb
lib/rmt/deduplicator.rb
lib/rmt/mirror.rb
lib/rmt/mirror/base.rb
lib/rmt/mirror/debian.rb
lib/rmt/mirror/repomd.rb
package/obs/rmt.conf
spec/lib/rmt/cli/base_spec.rb
spec/lib/rmt/cli/export_spec.rb
spec/lib/rmt/cli/import_spec.rb
spec/lib/rmt/cli/mirror_spec.rb
spec/lib/rmt/deduplicator_spec.rb
spec/lib/rmt/mirror/base_spec.rb
spec/lib/rmt/mirror/debian_spec.rb
spec/lib/rmt/mirror/license_spec.rb
spec/lib/rmt/mirror/repomd_spec.rb
spec/lib/rmt/mirror_spec.rb

This PR is part of our code sprint: https://trello.com/c/hU27QHob/3134-rdeb-sprint-tracker
**The whole changeset is:**
[[1/5] Prepare code sprint and implement repository type detection](https://github.com/SUSE/rmt/pull/1066)
[[2/5] Add flat debian mirroring support to RMT](https://github.com/SUSE/rmt/pull/1057)
[[3/5] Refactor suma mirroring](https://github.com/SUSE/rmt/pull/1059)
[[4/5] Refactor repomd mirroring](https://github.com/SUSE/rmt/pull/1060)
[[5/5] Fixes and cleanup](https://github.com/SUSE/rmt/pull/1067)
[[6/6] Nested debian repository support](https://github.com/SUSE/rmt/pull/1070)
**DO NOT MERGE UNTIL COMPLETELY READY**

[5/x] Fixes & cleanup

---

.gitignore

Ignore sqlite db files

---

package/obs/rmt-server.changes
package/obs/rmt-server.spec

Fix build for Factory by adding user provides.

Add user provides to .spec file (contrib by dimstar@opensuse.org)

---

package/obs/rmt-server.changes

Changelog updates for rmt 2.15 release

---

engines/scc_proxy/lib/scc_proxy/engine.rb

Prevent logging authenticated system info if instance is not BYOS

Log byos only

---

package/obs/rmt-server.spec

Disabling `dwz` in package build

Disable dwz in build service

---

docs/smt_and_rmt.md

The table was out of date.
- Added RHEL 7 support
- Added Kubernetes deployment support

Update SMT comparison table with latest info

---

lib/rmt/cli/clean.rb

Fix clean package

---

package/obs/rmt-server.changes

Missing dash line was the reason rmt 2.16 was rejected.

Fix: add dotted line in changelog

---

Gemfile
Gemfile.lock
ci/rmt-configure
config/application.rb
config/environments/test.rb
config/routes.rb
engines/registry/README.md
engines/registry/app/controllers/registry/application_controller.rb
engines/registry/app/controllers/registry/registry_controller.rb
engines/registry/app/models/access_scope.rb
engines/registry/app/models/access_token.rb
engines/registry/app/models/catalog_client.rb
engines/registry/app/models/concerns/registry_client.rb
engines/registry/app/models/registry/authenticated_client.rb
engines/registry/app/models/registry/exceptions.rb
engines/registry/app/services/registry_catalog_service.rb
engines/registry/bin/rails
engines/registry/config/routes.rb
engines/registry/lib/registry.rb
engines/registry/lib/registry/engine.rb
engines/registry/lib/registry/version.rb
engines/registry/lib/tasks/registry.rake
engines/registry/spec/app/controllers/registry_controller_spec.rb
engines/registry/spec/app/models/access_scope_spec.rb
engines/registry/spec/app/models/registry/authenticated_client_spec.rb
engines/registry/spec/app/services/registry_catalog_service_spec.rb
engines/registry/spec/data/access_policy_yaml.yml
engines/registry/spec/factories/access_scope.rb
engines/registry/spec/requests/api/connect/v3/systems/activations_controller_spec.rb
package/files/nginx-pubcloud/nginx-https.conf

Re merging the changes after RMT 2.16 release

Apply same changes as reverted PR

---

engines/registration_sharing/package/rmt-server-trim-cache.service

We will handle the system cache different for access on the repository and registry path. File cache will be in locations determined by a file written from the rails app. The app will also set the expiry time of the cache. Update the scrubber to use the file written by RMT.
- [ x] **New Feature** (a non-breaking change which adds new functionality)
- [ x] RMT's test coverage remains at 100%.

Update cache scrubber

---

app/controllers/api/connect/v3/systems/products_controller.rb
spec/support/shared_examples/product_checks.rb

Re-fix repository id in missing mirrored repos

---

package/obs/rmt-server.changes
public/tools/rmt-client-setup-res

This change enable RES7-LTSS and OL7-LTSS clients to connect to rmt
None it is new feature.
- [ x ] **New Feature** (a non-breaking change which adds new functionality)
- [ x] I have provided comments for any hard-to-understand code.
- [ x] RMT's test coverage remains at 100%.
- [ x] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

rmt-client-setup-res now should support RES7-LTSS and OL7-LTSS clients

---

db/migrate/20240620111456_remove_ltss_7_from_products.rb
features/lockfile_spec.rb

Ticket about the change: https://trello.com/c/infKb5AQ/3401-enb-suse-liberty-linux-7-adjustments
Fixes # n/a

Create migration to remove ltss7 from products

---

package/obs/rmt-server.changes

include changelog for latest change

---

db/migrate/20240711154147_add_index_to_systems_system_token.rb
db/schema.rb
engines/scc_suma_api/app/controllers/scc_suma_api/scc_suma_api_controller.rb

Make system_token an index in systems table
* [bsc#1227131](https://bugzilla.suse.com/show_bug.cgi?id=1227131)

Add index to Systems table

---

PACKAGE.md

update + move container + helm release docs

---

engines/registry/app/models/access_scope.rb
engines/registry/spec/app/models/access_scope_spec.rb
package/obs/rmt-server.changes

Add test to check the header is sent

Add header to SCC endpoint

---

engines/scc_suma_api/spec/requests/scc_suma_api/scc_suma_api_controller_spec.rb

fix deprecated stub method

---

lib/rmt.rb
package/obs/rmt-server.changes
package/obs/rmt-server.spec

Version bump + changelog for 2.19

prepare 2.19 release

---

PACKAGE.md

Update helm-chart release process doc

---

package/obs/rmt-server.spec

Don't replace timers after install

---

PACKAGE.md

This is just an update as I got help from @ngetahun to build the obs package.

Update package documentation

---

package/obs/rmt-server.changes

Update the changes for 2.20 release

Add changes for v2.20 for pubcloud

---

engines/instance_verification/lib/instance_verification/providers/example.rb

Fix typo in comment

---

config/rmt.yml

Make RMT host configurable

---

lib/rmt.rb
package/obs/rmt-server.spec

Bump version for 2.20 test build

---

package/obs/rmt-server.changes

This release includes important bug fixes and enhancements for improved stability and functionality in RMT.
**Key changes:**
- Version 2.20
* RMT packaging: don't overwrite custom sync/mirror timer config on package update
* Extend column size for repository and file paths (bsc#1229152)
* Forward suseconnect client user-agents to SCC
* rmt-server-pubcloud:
* Fix LTSS product verification (bsc#1230154)
* Fix activations check when no product info is available (bsc#1230157)
* Fix Azure SCC connection (bsc#1233314)
* Deny access of Azure Basic type images to LTSS
* Allow SLE Micro system to access SLES repositories (bsc#1230419)
* Skip system token rotation in read-only APIs
* Enable RMT to handle the new dl.suse.com CDN domain (bsc#1234641)
* Clean up RMT metadata after repo update …

Finalize changes for v2.20 release

---

config/rmt.yml
lib/rmt.rb
lib/rmt/mirror/suma_product_tree.rb
package/obs/rmt-server.changes
package/obs/rmt-server.spec
spec/lib/rmt/mirror/suma_product_tree_spec.rb

Revert "Configure SUMA product tree base URL"

---

package/files/nginx/nginx-http.conf
package/files/nginx/nginx-https.conf

Fix nginx directory listing on /tools directory

---

engines/data_export/README.md
engines/data_export/lib/data_export/engine.rb
engines/data_export/lib/data_export/handlers/example.rb
engines/data_export/spec/requests/api/connect/v3/subscriptions/systems_controller_spec.rb
engines/data_export/spec/requests/api/connect/v3/systems/systems_controller_spec.rb

- Provide a description for use of the data export engine and how to use it
- Rename the update_info interface of the export engine to export_rmt_data

Export engine adjustments

---

db/migrate/20240729103525_update_proxy_byos_column_type.rb
db/migrate/20250319155325_backfill_update_proxy_byos_column_type.rb
db/schema.rb

Rewrite the 'update_proxy_byos_column_type' migration to make it compliant to 'strong_migrations' rules; adding a new column with a non-null default value is considered a "dangerous operation."
The issue was caught when running 'docker-compose up' for local development. The GitHub Actions pipeline doesn't run into this same issue, and since the migration has been merged, not issues with it have been reported; otherwise, a fresh-new installation of RMT would not be properly set up.
1. Change directories to this project's local clone on your local machine.
2. Pull the latest changes with `git pull`.
3. Without checking out the *git* branch, run `docker-compose up`.
4. Verify that the container `rmt` gets into a *forever-running* loop, trying to recover from the migration …

Rewrite update_proxy_byos migration

---

db/migrate/20240729103525_add_proxy_byos_mode_to_systems.rb
db/migrate/20240729103525_update_proxy_byos_column_type.rb
db/migrate/20250319155325_backfill_add_proxy_byos_mode_to_systems.rb
db/migrate/20250319155325_backfill_update_proxy_byos_column_type.rb

Move the backfill of the 'proxy_byos_mode' column to a separated migration. The previous changes on PR #1301 only created a new migration to backfill the default value of the column, but the original one still contained backfill logic.
Since a backfill migration was created ('strong_migrations' recommendation), this commit just aggregates all the backfill logic into a single migration, keeping column creation and updating its values separated.
Additionally, the migration files have been renamed according to [Rails naming conventions](https://guides.rubyonrails.org/active_record_migrations.html#adding-columns) and `strong_migrations` backfill naming suggestion.
1. Change directories to this project's local clone on your local machine.
2. Pull the latest changes with `git pull`.
3. Without …

fix: Rewrite migration for proxy byos mode column

---

engines/instance_verification/README.md

Update the README for the new cache info

Update README for the cache info

---

Gemfile
Gemfile.lock

update to latest puma version

---

engines/registry/app/models/access_scope.rb
engines/registry/app/models/registry/authenticated_client.rb
engines/registry/app/services/registry_catalog_service.rb
engines/registry/spec/app/models/access_scope_spec.rb
engines/registry/spec/app/services/registry_catalog_service_spec.rb

Do not raise/log a 500 error when there is no client
This Fixes #1302
* Related Issue / Ticket / Trello card: #1302 
using the registry should not log 500 errors

Handle null client

---

engines/data_export/lib/data_export/engine.rb
engines/data_export/spec/requests/api/connect/v3/systems/systems_controller_spec.rb

Do not export BYOS to the Firehose bucket
a BYOS system should not be sent to the bucket

Do not export BYOS systems to the Firehose bucket

---

engines/instance_verification/spec/requests/api/connect/v3/systems/products_controller_spec.rb
engines/scc_proxy/lib/scc_proxy/engine.rb

When activating the product, reach to SCC independently of the cache state update the cache accordingly to SCC response
Update tests
This fixes #1278  and makes the SCC query
Behaviour as expected for reducing SCC queries

Make SCC query and update cache

---

engines/instance_verification/spec/requests/api/connect/v3/systems/products_controller_spec.rb
engines/scc_proxy/lib/scc_proxy/engine.rb

Check the cache before making a request to SCC
Refactor the cache check, so activate and upgrade product use the same code
Update registration code to the test
Update the test to allow cache check
* Related Issue / Ticket / Trello card: [reduce SCC queries](https://trello.com/c/62VdOel1)  [jira ticket](https://jira.suse.com/browse/PCT-473)
Upgrade a product present on the cache, it should not query the SCC

Add upgrade cache check

---

lib/rmt.rb
package/obs/rmt-server.changes
package/obs/rmt-server.spec

Update version and update changelog for public cloud

---

package/obs/rmt-server.changes

Add note about rack update

---

package/obs/rmt-server.changes

Adding more details to the changelog

Add CVE numbers to changelog

---

lib/rmt.rb
package/obs/rmt-server.changes
package/obs/rmt-server.spec

* Related Issue / Ticket / Trello card: https://trello.com/c/U4bNiEUu/3963-zypp-rmt-delta-rpms-issue

Update to version 2.23

---

PACKAGE.md

Add link to BCI scripts for building container image
